// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	game "internal.proto/pb/game"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Chat 相關 message 用於 gate forward 路徑（Pack.Info）
// ChannelReq 訂閱／取消訂閱頻道共用請求（method 區分 subscribeChannel / unsubscribeChannel）
type ChannelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`        // 玩家 UID
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // 頻道名稱，格式：room/{svt}/{rid}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelReq) Reset() {
	*x = ChannelReq{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelReq) ProtoMessage() {}

func (x *ChannelReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelReq.ProtoReflect.Descriptor instead.
func (*ChannelReq) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChannelReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// ChannelResp 訂閱／取消訂閱頻道共用回應；錯誤訊息通過 gate.Pack.msg 傳遞
type ChannelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"` // 頻道名稱
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`        // 玩家 UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResp) Reset() {
	*x = ChannelResp{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResp) ProtoMessage() {}

func (x *ChannelResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResp.ProtoReflect.Descriptor instead.
func (*ChannelResp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelResp) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelResp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// UnsubscribeAllChannels_Req 取消所有頻道訂閱請求
type UnsubscribeAllChannels_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 玩家 UID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeAllChannels_Req) Reset() {
	*x = UnsubscribeAllChannels_Req{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeAllChannels_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeAllChannels_Req) ProtoMessage() {}

func (x *UnsubscribeAllChannels_Req) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeAllChannels_Req.ProtoReflect.Descriptor instead.
func (*UnsubscribeAllChannels_Req) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UnsubscribeAllChannels_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// UnsubscribeAllChannels_Resp 取消所有頻道訂閱回應
// 錯誤訊息通過 gate.Pack.msg 傳遞
type UnsubscribeAllChannels_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                   // 玩家 UID
	ChannelCount  uint32                 `protobuf:"varint,2,opt,name=channelCount,proto3" json:"channelCount,omitempty"` // 取消訂閱的頻道數量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeAllChannels_Resp) Reset() {
	*x = UnsubscribeAllChannels_Resp{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeAllChannels_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeAllChannels_Resp) ProtoMessage() {}

func (x *UnsubscribeAllChannels_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeAllChannels_Resp.ProtoReflect.Descriptor instead.
func (*UnsubscribeAllChannels_Resp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeAllChannels_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UnsubscribeAllChannels_Resp) GetChannelCount() uint32 {
	if x != nil {
		return x.ChannelCount
	}
	return 0
}

// SendMessage_Req 發送訊息到頻道請求
type SendMessage_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`        // 發送者 UID
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // 頻道名稱，格式：room/{svt}/{rid}
	Message       *game.Chat             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 聊天訊息（包含 nickname 和 message）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage_Req) Reset() {
	*x = SendMessage_Req{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_Req) ProtoMessage() {}

func (x *SendMessage_Req) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_Req.ProtoReflect.Descriptor instead.
func (*SendMessage_Req) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessage_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SendMessage_Req) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendMessage_Req) GetMessage() *game.Chat {
	if x != nil {
		return x.Message
	}
	return nil
}

// SendMessage_Resp 發送訊息到頻道回應
// 錯誤訊息通過 gate.Pack.msg 傳遞
type SendMessage_Resp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Channel        string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`                // 頻道名稱
	RecipientCount uint32                 `protobuf:"varint,2,opt,name=recipientCount,proto3" json:"recipientCount,omitempty"` // 接收訊息的訂閱者數量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessage_Resp) Reset() {
	*x = SendMessage_Resp{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage_Resp) ProtoMessage() {}

func (x *SendMessage_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage_Resp.ProtoReflect.Descriptor instead.
func (*SendMessage_Resp) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessage_Resp) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendMessage_Resp) GetRecipientCount() uint32 {
	if x != nil {
		return x.RecipientCount
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\x1a\n" +
	"game.proto\"8\n" +
	"\n" +
	"ChannelReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"9\n" +
	"\vChannelResp\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\".\n" +
	"\x1aUnsubscribeAllChannels_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"S\n" +
	"\x1bUnsubscribeAllChannels_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\"\n" +
	"\fchannelCount\x18\x02 \x01(\rR\fchannelCount\"c\n" +
	"\x0fSendMessage_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12$\n" +
	"\amessage\x18\x03 \x01(\v2\n" +
	".game.ChatR\amessage\"T\n" +
	"\x10SendMessage_Resp\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12&\n" +
	"\x0erecipientCount\x18\x02 \x01(\rR\x0erecipientCountB\x1dZ\x1binternal.proto/pb/chat;chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chat_proto_goTypes = []any{
	(*ChannelReq)(nil),                  // 0: chat.ChannelReq
	(*ChannelResp)(nil),                 // 1: chat.ChannelResp
	(*UnsubscribeAllChannels_Req)(nil),  // 2: chat.UnsubscribeAllChannels_Req
	(*UnsubscribeAllChannels_Resp)(nil), // 3: chat.UnsubscribeAllChannels_Resp
	(*SendMessage_Req)(nil),             // 4: chat.SendMessage_Req
	(*SendMessage_Resp)(nil),            // 5: chat.SendMessage_Resp
	(*game.Chat)(nil),                   // 6: game.Chat
}
var file_chat_proto_depIdxs = []int32{
	6, // 0: chat.SendMessage_Req.message:type_name -> game.Chat
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
