// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: purchase.proto

package purchase

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetList：client 取得所有可購買品項
type GetList_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetList_Req) Reset() {
	*x = GetList_Req{}
	mi := &file_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetList_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetList_Req) ProtoMessage() {}

func (x *GetList_Req) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetList_Req.ProtoReflect.Descriptor instead.
func (*GetList_Req) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{0}
}

type GetList_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PurchaseItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetList_Resp) Reset() {
	*x = GetList_Resp{}
	mi := &file_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetList_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetList_Resp) ProtoMessage() {}

func (x *GetList_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetList_Resp.ProtoReflect.Descriptor instead.
func (*GetList_Resp) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *GetList_Resp) GetItems() []*PurchaseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PurchaseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoinType      uint32                 `protobuf:"varint,4,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	CoinAmount    int32                  `protobuf:"varint,5,opt,name=coin_amount,json=coinAmount,proto3" json:"coin_amount,omitempty"` // 可擴充：價格、貨幣、訂閱週期等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseItem) Reset() {
	*x = PurchaseItem{}
	mi := &file_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseItem) ProtoMessage() {}

func (x *PurchaseItem) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseItem.ProtoReflect.Descriptor instead.
func (*PurchaseItem) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *PurchaseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PurchaseItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PurchaseItem) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *PurchaseItem) GetCoinAmount() int32 {
	if x != nil {
		return x.CoinAmount
	}
	return 0
}

// Buy：client 購買品項
type Buy_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buy_Req) Reset() {
	*x = Buy_Req{}
	mi := &file_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buy_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buy_Req) ProtoMessage() {}

func (x *Buy_Req) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buy_Req.ProtoReflect.Descriptor instead.
func (*Buy_Req) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *Buy_Req) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type Buy_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	NewBalance    int32                  `protobuf:"varint,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buy_Resp) Reset() {
	*x = Buy_Resp{}
	mi := &file_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buy_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buy_Resp) ProtoMessage() {}

func (x *Buy_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buy_Resp.ProtoReflect.Descriptor instead.
func (*Buy_Resp) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *Buy_Resp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Buy_Resp) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *Buy_Resp) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

// PlayerAssets：service 廣播玩家資產（method: playerAssets）
type PlayerAssets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	Coin          int32                  `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"` // 可擴充：道具、訂閱狀態等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAssets) Reset() {
	*x = PlayerAssets{}
	mi := &file_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAssets) ProtoMessage() {}

func (x *PlayerAssets) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAssets.ProtoReflect.Descriptor instead.
func (*PlayerAssets) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerAssets) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerAssets) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *PlayerAssets) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

var File_purchase_proto protoreflect.FileDescriptor

const file_purchase_proto_rawDesc = "" +
	"\n" +
	"\x0epurchase.proto\x12\bpurchase\"\r\n" +
	"\vGetList_Req\"<\n" +
	"\fGetList_Resp\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.purchase.PurchaseItemR\x05items\"\xa1\x01\n" +
	"\fPurchaseItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcoin_type\x18\x04 \x01(\rR\bcoinType\x12\x1f\n" +
	"\vcoin_amount\x18\x05 \x01(\x05R\n" +
	"coinAmount\"(\n" +
	"\aBuy_Req\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"c\n" +
	"\bBuy_Resp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tcoin_type\x18\x02 \x01(\rR\bcoinType\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\x05R\n" +
	"newBalance\"Q\n" +
	"\fPlayerAssets\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1b\n" +
	"\tcoin_type\x18\x02 \x01(\rR\bcoinType\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\x05R\x04coinB%Z#internal.proto/pb/purchase;purchaseb\x06proto3"

var (
	file_purchase_proto_rawDescOnce sync.Once
	file_purchase_proto_rawDescData []byte
)

func file_purchase_proto_rawDescGZIP() []byte {
	file_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)))
	})
	return file_purchase_proto_rawDescData
}

var file_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_purchase_proto_goTypes = []any{
	(*GetList_Req)(nil),  // 0: purchase.GetList_Req
	(*GetList_Resp)(nil), // 1: purchase.GetList_Resp
	(*PurchaseItem)(nil), // 2: purchase.PurchaseItem
	(*Buy_Req)(nil),      // 3: purchase.Buy_Req
	(*Buy_Resp)(nil),     // 4: purchase.Buy_Resp
	(*PlayerAssets)(nil), // 5: purchase.PlayerAssets
}
var file_purchase_proto_depIdxs = []int32{
	2, // 0: purchase.GetList_Resp.items:type_name -> purchase.PurchaseItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_purchase_proto_init() }
func file_purchase_proto_init() {
	if File_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_proto_depIdxs,
		MessageInfos:      file_purchase_proto_msgTypes,
	}.Build()
	File_purchase_proto = out.File
	file_purchase_proto_goTypes = nil
	file_purchase_proto_depIdxs = nil
}
