// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: history.proto

package history

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SaveGameHistory_Req 儲存遊戲記錄的請求
type SaveGameHistory_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                        // 玩家 UID
	GameType      string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`               // 遊戲類型（svt），決定寫入哪張表，如 "baccarat", "holdem"
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                     // 房間 ID
	RoundNumber   uint32                 `protobuf:"varint,4,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`     // 回合數
	RoundSerial   string                 `protobuf:"bytes,8,opt,name=round_serial,json=roundSerial,proto3" json:"round_serial,omitempty"`      // 回合流水號（同一回合的所有玩家記錄使用相同的流水號）
	BetAmount     int64                  `protobuf:"varint,5,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`           // 總下注金額
	WinAmount     int64                  `protobuf:"varint,6,opt,name=win_amount,json=winAmount,proto3" json:"win_amount,omitempty"`           // 總贏得金額（含本金返還）
	GameDataJson  string                 `protobuf:"bytes,7,opt,name=game_data_json,json=gameDataJson,proto3" json:"game_data_json,omitempty"` // 遊戲詳情（JSON 字串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameHistory_Req) Reset() {
	*x = SaveGameHistory_Req{}
	mi := &file_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameHistory_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameHistory_Req) ProtoMessage() {}

func (x *SaveGameHistory_Req) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameHistory_Req.ProtoReflect.Descriptor instead.
func (*SaveGameHistory_Req) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{0}
}

func (x *SaveGameHistory_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SaveGameHistory_Req) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *SaveGameHistory_Req) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SaveGameHistory_Req) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *SaveGameHistory_Req) GetRoundSerial() string {
	if x != nil {
		return x.RoundSerial
	}
	return ""
}

func (x *SaveGameHistory_Req) GetBetAmount() int64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *SaveGameHistory_Req) GetWinAmount() int64 {
	if x != nil {
		return x.WinAmount
	}
	return 0
}

func (x *SaveGameHistory_Req) GetGameDataJson() string {
	if x != nil {
		return x.GameDataJson
	}
	return ""
}

// SaveGameHistory_Resp 儲存遊戲記錄的回應
type SaveGameHistory_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HistoryId     int64                  `protobuf:"varint,1,opt,name=history_id,json=historyId,proto3" json:"history_id,omitempty"` // 新建記錄的 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGameHistory_Resp) Reset() {
	*x = SaveGameHistory_Resp{}
	mi := &file_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGameHistory_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGameHistory_Resp) ProtoMessage() {}

func (x *SaveGameHistory_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGameHistory_Resp.ProtoReflect.Descriptor instead.
func (*SaveGameHistory_Resp) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{1}
}

func (x *SaveGameHistory_Resp) GetHistoryId() int64 {
	if x != nil {
		return x.HistoryId
	}
	return 0
}

// GetGameHistory_Req 查詢遊戲記錄的請求
type GetGameHistory_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`    // 遊戲類型（必填）
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                             // 玩家 UID（可選）
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 開始日期（ISO 格式，可選）
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 結束日期（ISO 格式，可選）
	Page          uint32                 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                           // 頁碼（預設 1）
	PageSize      uint32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每頁筆數（預設 20）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistory_Req) Reset() {
	*x = GetGameHistory_Req{}
	mi := &file_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistory_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistory_Req) ProtoMessage() {}

func (x *GetGameHistory_Req) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistory_Req.ProtoReflect.Descriptor instead.
func (*GetGameHistory_Req) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameHistory_Req) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GetGameHistory_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetGameHistory_Req) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetGameHistory_Req) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetGameHistory_Req) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameHistory_Req) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GameHistoryRecord 遊戲記錄
type GameHistoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                          // 記錄 ID
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                        // 玩家 UID
	FirebaseUid   string                 `protobuf:"bytes,3,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"`      // Firebase UID
	RoomId        string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                     // 房間 ID
	RoundNumber   uint32                 `protobuf:"varint,5,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`     // 回合數
	RoundSerial   string                 `protobuf:"bytes,11,opt,name=round_serial,json=roundSerial,proto3" json:"round_serial,omitempty"`     // 回合流水號（同一回合的所有玩家記錄使用相同的流水號）
	BetAmount     int64                  `protobuf:"varint,6,opt,name=bet_amount,json=betAmount,proto3" json:"bet_amount,omitempty"`           // 總下注金額
	WinAmount     int64                  `protobuf:"varint,7,opt,name=win_amount,json=winAmount,proto3" json:"win_amount,omitempty"`           // 總贏得金額
	NetResult     int64                  `protobuf:"varint,8,opt,name=net_result,json=netResult,proto3" json:"net_result,omitempty"`           // 淨收益
	GameDataJson  string                 `protobuf:"bytes,9,opt,name=game_data_json,json=gameDataJson,proto3" json:"game_data_json,omitempty"` // 遊戲詳情（JSON 字串）
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // 創建時間（ISO 格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameHistoryRecord) Reset() {
	*x = GameHistoryRecord{}
	mi := &file_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameHistoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameHistoryRecord) ProtoMessage() {}

func (x *GameHistoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameHistoryRecord.ProtoReflect.Descriptor instead.
func (*GameHistoryRecord) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{3}
}

func (x *GameHistoryRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameHistoryRecord) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GameHistoryRecord) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

func (x *GameHistoryRecord) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GameHistoryRecord) GetRoundNumber() uint32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *GameHistoryRecord) GetRoundSerial() string {
	if x != nil {
		return x.RoundSerial
	}
	return ""
}

func (x *GameHistoryRecord) GetBetAmount() int64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *GameHistoryRecord) GetWinAmount() int64 {
	if x != nil {
		return x.WinAmount
	}
	return 0
}

func (x *GameHistoryRecord) GetNetResult() int64 {
	if x != nil {
		return x.NetResult
	}
	return 0
}

func (x *GameHistoryRecord) GetGameDataJson() string {
	if x != nil {
		return x.GameDataJson
	}
	return ""
}

func (x *GameHistoryRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GetGameHistory_Resp 查詢遊戲記錄的回應
type GetGameHistory_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*GameHistoryRecord   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`                          // 記錄列表
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                             // 總筆數
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                               // 當前頁碼
	PageSize      uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每頁筆數
	TotalPages    uint32                 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // 總頁數
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameHistory_Resp) Reset() {
	*x = GetGameHistory_Resp{}
	mi := &file_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameHistory_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameHistory_Resp) ProtoMessage() {}

func (x *GetGameHistory_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameHistory_Resp.ProtoReflect.Descriptor instead.
func (*GetGameHistory_Resp) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameHistory_Resp) GetRecords() []*GameHistoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetGameHistory_Resp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetGameHistory_Resp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGameHistory_Resp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetGameHistory_Resp) GetTotalPages() uint32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// GetGameStats_Req 取得遊戲統計的請求
type GetGameStats_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"` // 遊戲類型（可選，空字串表示所有遊戲）
	Days          uint32                 `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`                        // 統計天數（預設 30）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStats_Req) Reset() {
	*x = GetGameStats_Req{}
	mi := &file_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStats_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStats_Req) ProtoMessage() {}

func (x *GetGameStats_Req) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStats_Req.ProtoReflect.Descriptor instead.
func (*GetGameStats_Req) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameStats_Req) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GetGameStats_Req) GetDays() uint32 {
	if x != nil {
		return x.Days
	}
	return 0
}

// GameStats 遊戲統計資料
type GameStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameType      string                 `protobuf:"bytes,1,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`                 // 遊戲類型
	TotalGames    uint32                 `protobuf:"varint,2,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`          // 總遊戲數
	UniquePlayers uint32                 `protobuf:"varint,3,opt,name=unique_players,json=uniquePlayers,proto3" json:"unique_players,omitempty"` // 唯一玩家數
	TotalBet      int64                  `protobuf:"varint,4,opt,name=total_bet,json=totalBet,proto3" json:"total_bet,omitempty"`                // 總下注金額
	TotalPayout   int64                  `protobuf:"varint,5,opt,name=total_payout,json=totalPayout,proto3" json:"total_payout,omitempty"`       // 總支出金額
	HouseProfit   int64                  `protobuf:"varint,6,opt,name=house_profit,json=houseProfit,proto3" json:"house_profit,omitempty"`       // 莊家利潤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStats) Reset() {
	*x = GameStats{}
	mi := &file_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStats) ProtoMessage() {}

func (x *GameStats) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStats.ProtoReflect.Descriptor instead.
func (*GameStats) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{6}
}

func (x *GameStats) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *GameStats) GetTotalGames() uint32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *GameStats) GetUniquePlayers() uint32 {
	if x != nil {
		return x.UniquePlayers
	}
	return 0
}

func (x *GameStats) GetTotalBet() int64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *GameStats) GetTotalPayout() int64 {
	if x != nil {
		return x.TotalPayout
	}
	return 0
}

func (x *GameStats) GetHouseProfit() int64 {
	if x != nil {
		return x.HouseProfit
	}
	return 0
}

// GetGameStats_Resp 取得遊戲統計的回應
type GetGameStats_Resp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Stats              []*GameStats           `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`                                                       // 統計資料列表
	SupportedGameTypes []string               `protobuf:"bytes,2,rep,name=supported_game_types,json=supportedGameTypes,proto3" json:"supported_game_types,omitempty"` // 支援的遊戲類型列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGameStats_Resp) Reset() {
	*x = GetGameStats_Resp{}
	mi := &file_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStats_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStats_Resp) ProtoMessage() {}

func (x *GetGameStats_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStats_Resp.ProtoReflect.Descriptor instead.
func (*GetGameStats_Resp) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameStats_Resp) GetStats() []*GameStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetGameStats_Resp) GetSupportedGameTypes() []string {
	if x != nil {
		return x.SupportedGameTypes
	}
	return nil
}

// GetPlayerStats_Req 取得玩家統計的請求
type GetPlayerStats_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                          // 玩家 UID（必填）
	GameType      string                 `protobuf:"bytes,2,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"` // 遊戲類型（可選，空字串表示所有遊戲）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStats_Req) Reset() {
	*x = GetPlayerStats_Req{}
	mi := &file_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStats_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStats_Req) ProtoMessage() {}

func (x *GetPlayerStats_Req) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStats_Req.ProtoReflect.Descriptor instead.
func (*GetPlayerStats_Req) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayerStats_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetPlayerStats_Req) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

// PlayerGameStats 玩家遊戲統計
type PlayerGameStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                   // 玩家 UID
	FirebaseUid   string                 `protobuf:"bytes,2,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"` // Firebase UID
	GameType      string                 `protobuf:"bytes,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`          // 遊戲類型
	TotalGames    uint32                 `protobuf:"varint,4,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`   // 總遊戲數
	TotalBet      int64                  `protobuf:"varint,5,opt,name=total_bet,json=totalBet,proto3" json:"total_bet,omitempty"`         // 總下注金額
	TotalWin      int64                  `protobuf:"varint,6,opt,name=total_win,json=totalWin,proto3" json:"total_win,omitempty"`         // 總贏得金額
	NetProfit     int64                  `protobuf:"varint,7,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`      // 淨收益
	WinRate       float64                `protobuf:"fixed64,8,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`           // 勝率（百分比）
	LastPlayed    string                 `protobuf:"bytes,9,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`    // 最後遊玩時間（ISO 格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerGameStats) Reset() {
	*x = PlayerGameStats{}
	mi := &file_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerGameStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerGameStats) ProtoMessage() {}

func (x *PlayerGameStats) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerGameStats.ProtoReflect.Descriptor instead.
func (*PlayerGameStats) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerGameStats) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerGameStats) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

func (x *PlayerGameStats) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *PlayerGameStats) GetTotalGames() uint32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *PlayerGameStats) GetTotalBet() int64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *PlayerGameStats) GetTotalWin() int64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *PlayerGameStats) GetNetProfit() int64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

func (x *PlayerGameStats) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *PlayerGameStats) GetLastPlayed() string {
	if x != nil {
		return x.LastPlayed
	}
	return ""
}

// GetPlayerStats_Resp 取得玩家統計的回應
type GetPlayerStats_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*PlayerGameStats     `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"` // 統計資料列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerStats_Resp) Reset() {
	*x = GetPlayerStats_Resp{}
	mi := &file_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerStats_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerStats_Resp) ProtoMessage() {}

func (x *GetPlayerStats_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerStats_Resp.ProtoReflect.Descriptor instead.
func (*GetPlayerStats_Resp) Descriptor() ([]byte, []int) {
	return file_history_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerStats_Resp) GetStats() []*PlayerGameStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_history_proto protoreflect.FileDescriptor

const file_history_proto_rawDesc = "" +
	"\n" +
	"\rhistory.proto\x12\ahistory\"\x87\x02\n" +
	"\x13SaveGameHistory_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12!\n" +
	"\fround_number\x18\x04 \x01(\rR\vroundNumber\x12!\n" +
	"\fround_serial\x18\b \x01(\tR\vroundSerial\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\x05 \x01(\x03R\tbetAmount\x12\x1d\n" +
	"\n" +
	"win_amount\x18\x06 \x01(\x03R\twinAmount\x12$\n" +
	"\x0egame_data_json\x18\a \x01(\tR\fgameDataJson\"5\n" +
	"\x14SaveGameHistory_Resp\x12\x1d\n" +
	"\n" +
	"history_id\x18\x01 \x01(\x03R\thistoryId\"\xae\x01\n" +
	"\x12GetGameHistory_Req\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\x05 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\rR\bpageSize\"\xd9\x02\n" +
	"\x11GameHistoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12!\n" +
	"\ffirebase_uid\x18\x03 \x01(\tR\vfirebaseUid\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\x12!\n" +
	"\fround_number\x18\x05 \x01(\rR\vroundNumber\x12!\n" +
	"\fround_serial\x18\v \x01(\tR\vroundSerial\x12\x1d\n" +
	"\n" +
	"bet_amount\x18\x06 \x01(\x03R\tbetAmount\x12\x1d\n" +
	"\n" +
	"win_amount\x18\a \x01(\x03R\twinAmount\x12\x1d\n" +
	"\n" +
	"net_result\x18\b \x01(\x03R\tnetResult\x12$\n" +
	"\x0egame_data_json\x18\t \x01(\tR\fgameDataJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xb3\x01\n" +
	"\x13GetGameHistory_Resp\x124\n" +
	"\arecords\x18\x01 \x03(\v2\x1a.history.GameHistoryRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\rR\n" +
	"totalPages\"C\n" +
	"\x10GetGameStats_Req\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x12\n" +
	"\x04days\x18\x02 \x01(\rR\x04days\"\xd3\x01\n" +
	"\tGameStats\x12\x1b\n" +
	"\tgame_type\x18\x01 \x01(\tR\bgameType\x12\x1f\n" +
	"\vtotal_games\x18\x02 \x01(\rR\n" +
	"totalGames\x12%\n" +
	"\x0eunique_players\x18\x03 \x01(\rR\runiquePlayers\x12\x1b\n" +
	"\ttotal_bet\x18\x04 \x01(\x03R\btotalBet\x12!\n" +
	"\ftotal_payout\x18\x05 \x01(\x03R\vtotalPayout\x12!\n" +
	"\fhouse_profit\x18\x06 \x01(\x03R\vhouseProfit\"o\n" +
	"\x11GetGameStats_Resp\x12(\n" +
	"\x05stats\x18\x01 \x03(\v2\x12.history.GameStatsR\x05stats\x120\n" +
	"\x14supported_game_types\x18\x02 \x03(\tR\x12supportedGameTypes\"C\n" +
	"\x12GetPlayerStats_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1b\n" +
	"\tgame_type\x18\x02 \x01(\tR\bgameType\"\x99\x02\n" +
	"\x0fPlayerGameStats\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12!\n" +
	"\ffirebase_uid\x18\x02 \x01(\tR\vfirebaseUid\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\tR\bgameType\x12\x1f\n" +
	"\vtotal_games\x18\x04 \x01(\rR\n" +
	"totalGames\x12\x1b\n" +
	"\ttotal_bet\x18\x05 \x01(\x03R\btotalBet\x12\x1b\n" +
	"\ttotal_win\x18\x06 \x01(\x03R\btotalWin\x12\x1d\n" +
	"\n" +
	"net_profit\x18\a \x01(\x03R\tnetProfit\x12\x19\n" +
	"\bwin_rate\x18\b \x01(\x01R\awinRate\x12\x1f\n" +
	"\vlast_played\x18\t \x01(\tR\n" +
	"lastPlayed\"E\n" +
	"\x13GetPlayerStats_Resp\x12.\n" +
	"\x05stats\x18\x01 \x03(\v2\x18.history.PlayerGameStatsR\x05statsB#Z!internal.proto/pb/history;historyb\x06proto3"

var (
	file_history_proto_rawDescOnce sync.Once
	file_history_proto_rawDescData []byte
)

func file_history_proto_rawDescGZIP() []byte {
	file_history_proto_rawDescOnce.Do(func() {
		file_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)))
	})
	return file_history_proto_rawDescData
}

var file_history_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_history_proto_goTypes = []any{
	(*SaveGameHistory_Req)(nil),  // 0: history.SaveGameHistory_Req
	(*SaveGameHistory_Resp)(nil), // 1: history.SaveGameHistory_Resp
	(*GetGameHistory_Req)(nil),   // 2: history.GetGameHistory_Req
	(*GameHistoryRecord)(nil),    // 3: history.GameHistoryRecord
	(*GetGameHistory_Resp)(nil),  // 4: history.GetGameHistory_Resp
	(*GetGameStats_Req)(nil),     // 5: history.GetGameStats_Req
	(*GameStats)(nil),            // 6: history.GameStats
	(*GetGameStats_Resp)(nil),    // 7: history.GetGameStats_Resp
	(*GetPlayerStats_Req)(nil),   // 8: history.GetPlayerStats_Req
	(*PlayerGameStats)(nil),      // 9: history.PlayerGameStats
	(*GetPlayerStats_Resp)(nil),  // 10: history.GetPlayerStats_Resp
}
var file_history_proto_depIdxs = []int32{
	3, // 0: history.GetGameHistory_Resp.records:type_name -> history.GameHistoryRecord
	6, // 1: history.GetGameStats_Resp.stats:type_name -> history.GameStats
	9, // 2: history.GetPlayerStats_Resp.stats:type_name -> history.PlayerGameStats
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_history_proto_init() }
func file_history_proto_init() {
	if File_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_history_proto_rawDesc), len(file_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_history_proto_goTypes,
		DependencyIndexes: file_history_proto_depIdxs,
		MessageInfos:      file_history_proto_msgTypes,
	}.Build()
	File_history_proto = out.File
	file_history_proto_goTypes = nil
	file_history_proto_depIdxs = nil
}
