// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: air_museum.proto

package air_museum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GamePhase 遊戲階段（可入桌／Demo／遊戲中／滿員）
type GamePhase int32

const (
	GamePhase_GAME_PHASE_UNSPECIFIED   GamePhase = 0
	GamePhase_GAME_PHASE_WAITING_ENTRY GamePhase = 1 // 可入桌，等待玩家 entry
	GamePhase_GAME_PHASE_DEMO          GamePhase = 2 // Demo 狀態
	GamePhase_GAME_PHASE_PLAYING       GamePhase = 3 // 遊戲中
	GamePhase_GAME_PHASE_FULL          GamePhase = 4 // 滿員
)

// Enum value maps for GamePhase.
var (
	GamePhase_name = map[int32]string{
		0: "GAME_PHASE_UNSPECIFIED",
		1: "GAME_PHASE_WAITING_ENTRY",
		2: "GAME_PHASE_DEMO",
		3: "GAME_PHASE_PLAYING",
		4: "GAME_PHASE_FULL",
	}
	GamePhase_value = map[string]int32{
		"GAME_PHASE_UNSPECIFIED":   0,
		"GAME_PHASE_WAITING_ENTRY": 1,
		"GAME_PHASE_DEMO":          2,
		"GAME_PHASE_PLAYING":       3,
		"GAME_PHASE_FULL":          4,
	}
)

func (x GamePhase) Enum() *GamePhase {
	p := new(GamePhase)
	*p = x
	return p
}

func (x GamePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_air_museum_proto_enumTypes[0].Descriptor()
}

func (GamePhase) Type() protoreflect.EnumType {
	return &file_air_museum_proto_enumTypes[0]
}

func (x GamePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePhase.Descriptor instead.
func (GamePhase) EnumDescriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{0}
}

// GameState 用於 pushGameState（投影機→Server）與 gameStateEvent（Server→所有 player）
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         GamePhase              `protobuf:"varint,1,opt,name=phase,proto3,enum=air_museum.GamePhase" json:"phase,omitempty"`
	CountdownSec  *int32                 `protobuf:"varint,2,opt,name=countdown_sec,json=countdownSec,proto3,oneof" json:"countdown_sec,omitempty"` // 可選：倒數秒數
	PlayerCount   *uint32                `protobuf:"varint,3,opt,name=player_count,json=playerCount,proto3,oneof" json:"player_count,omitempty"`    // 可選：當前玩家人數
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_air_museum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_air_museum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetPhase() GamePhase {
	if x != nil {
		return x.Phase
	}
	return GamePhase_GAME_PHASE_UNSPECIFIED
}

func (x *GameState) GetCountdownSec() int32 {
	if x != nil && x.CountdownSec != nil {
		return *x.CountdownSec
	}
	return 0
}

func (x *GameState) GetPlayerCount() uint32 {
	if x != nil && x.PlayerCount != nil {
		return *x.PlayerCount
	}
	return 0
}

// PlayerInput 手柄輸入，用於 notify/input；uid 由 Server 轉發給投影機時填入
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                   // 手柄送時可不填，Server 轉發時填入
	AxisX         float32                `protobuf:"fixed32,2,opt,name=axis_x,json=axisX,proto3" json:"axis_x,omitempty"` // 左右，建議 -1～1
	AxisY         float32                `protobuf:"fixed32,3,opt,name=axis_y,json=axisY,proto3" json:"axis_y,omitempty"` // 上下，建議 -1～1
	Seq           uint32                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`                   // 序號
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_air_museum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_air_museum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInput) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInput) GetAxisX() float32 {
	if x != nil {
		return x.AxisX
	}
	return 0
}

func (x *PlayerInput) GetAxisY() float32 {
	if x != nil {
		return x.AxisY
	}
	return 0
}

func (x *PlayerInput) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_air_museum_proto protoreflect.FileDescriptor

const file_air_museum_proto_rawDesc = "" +
	"\n" +
	"\x10air_museum.proto\x12\n" +
	"air_museum\"\xad\x01\n" +
	"\tGameState\x12+\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x15.air_museum.GamePhaseR\x05phase\x12(\n" +
	"\rcountdown_sec\x18\x02 \x01(\x05H\x00R\fcountdownSec\x88\x01\x01\x12&\n" +
	"\fplayer_count\x18\x03 \x01(\rH\x01R\vplayerCount\x88\x01\x01B\x10\n" +
	"\x0e_countdown_secB\x0f\n" +
	"\r_player_count\"_\n" +
	"\vPlayerInput\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x15\n" +
	"\x06axis_x\x18\x02 \x01(\x02R\x05axisX\x12\x15\n" +
	"\x06axis_y\x18\x03 \x01(\x02R\x05axisY\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\rR\x03seq*\x87\x01\n" +
	"\tGamePhase\x12\x1a\n" +
	"\x16GAME_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18GAME_PHASE_WAITING_ENTRY\x10\x01\x12\x13\n" +
	"\x0fGAME_PHASE_DEMO\x10\x02\x12\x16\n" +
	"\x12GAME_PHASE_PLAYING\x10\x03\x12\x13\n" +
	"\x0fGAME_PHASE_FULL\x10\x04B)Z'internal.proto/pb/air_museum;air_museumb\x06proto3"

var (
	file_air_museum_proto_rawDescOnce sync.Once
	file_air_museum_proto_rawDescData []byte
)

func file_air_museum_proto_rawDescGZIP() []byte {
	file_air_museum_proto_rawDescOnce.Do(func() {
		file_air_museum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_air_museum_proto_rawDesc), len(file_air_museum_proto_rawDesc)))
	})
	return file_air_museum_proto_rawDescData
}

var file_air_museum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_air_museum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_air_museum_proto_goTypes = []any{
	(GamePhase)(0),      // 0: air_museum.GamePhase
	(*GameState)(nil),   // 1: air_museum.GameState
	(*PlayerInput)(nil), // 2: air_museum.PlayerInput
}
var file_air_museum_proto_depIdxs = []int32{
	0, // 0: air_museum.GameState.phase:type_name -> air_museum.GamePhase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_air_museum_proto_init() }
func file_air_museum_proto_init() {
	if File_air_museum_proto != nil {
		return
	}
	file_air_museum_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_air_museum_proto_rawDesc), len(file_air_museum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_air_museum_proto_goTypes,
		DependencyIndexes: file_air_museum_proto_depIdxs,
		EnumInfos:         file_air_museum_proto_enumTypes,
		MessageInfos:      file_air_museum_proto_msgTypes,
	}.Build()
	File_air_museum_proto = out.File
	file_air_museum_proto_goTypes = nil
	file_air_museum_proto_depIdxs = nil
}
