// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 房間類型枚舉
type RoomType int32

const (
	RoomType_PUBLIC     RoomType = 0 // 公開房間
	RoomType_PRIVATE    RoomType = 1 // 私人房間
	RoomType_TOURNAMENT RoomType = 2 // 比賽房間
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "PUBLIC",
		1: "PRIVATE",
		2: "TOURNAMENT",
	}
	RoomType_value = map[string]int32{
		"PUBLIC":     0,
		"PRIVATE":    1,
		"TOURNAMENT": 2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

// MatchEntry：entry 請求 payload（plan-simplify-match-dispatch：湊桌必須帶 rule，未傳則回傳錯誤）
type MatchEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`              // 服務類型（如 "holdem"、"baccarat"）
	MinPlayer     uint32                 `protobuf:"varint,2,opt,name=minPlayer,proto3" json:"minPlayer,omitempty"` // 最少玩家數
	MaxPlayer     uint32                 `protobuf:"varint,3,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"` // 最多玩家數
	Player        *Player                `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`        // 進入的玩家本人（單一）
	Rule          string                 `protobuf:"bytes,5,opt,name=rule,proto3" json:"rule,omitempty"`            // 湊桌規則（如 JSON）；為空時不得入隊，Game 推送錯誤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEntry) Reset() {
	*x = MatchEntry{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEntry) ProtoMessage() {}

func (x *MatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEntry.ProtoReflect.Descriptor instead.
func (*MatchEntry) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *MatchEntry) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *MatchEntry) GetMinPlayer() uint32 {
	if x != nil {
		return x.MinPlayer
	}
	return 0
}

func (x *MatchEntry) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *MatchEntry) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *MatchEntry) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

type MatchRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`                           // 房間 ID
	Svt           string                 `protobuf:"bytes,2,opt,name=svt,proto3" json:"svt,omitempty"`                           // 服務類型 ID（如 "baccarat"、"holdem"、"match"、"lobby"）
	MinPlayer     uint32                 `protobuf:"varint,3,opt,name=minPlayer,proto3" json:"minPlayer,omitempty"`              // 最少玩家數
	MaxPlayer     uint32                 `protobuf:"varint,4,opt,name=maxPlayer,proto3" json:"maxPlayer,omitempty"`              // 最多玩家數
	CreatedAt     uint32                 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`              // 房間創建時間（Unix 時間戳）
	Players       []*Player              `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`                   // 玩家列表
	RuleHash      string                 `protobuf:"bytes,7,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"` // 湊桌 queue 的 ruleHash，供 Game 註冊 matchable_rooms 用（CreateRoom 時由 Match 傳入）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRoom) Reset() {
	*x = MatchRoom{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRoom) ProtoMessage() {}

func (x *MatchRoom) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRoom.ProtoReflect.Descriptor instead.
func (*MatchRoom) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *MatchRoom) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *MatchRoom) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *MatchRoom) GetMinPlayer() uint32 {
	if x != nil {
		return x.MinPlayer
	}
	return 0
}

func (x *MatchRoom) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *MatchRoom) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MatchRoom) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchRoom) GetRuleHash() string {
	if x != nil {
		return x.RuleHash
	}
	return ""
}

// 玩家資訊
type Player struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 玩家基本資訊
	Uid           uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`           // 玩家 ID
	Nickname      string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`  // 玩家暱稱
	CoinType      uint32 `protobuf:"varint,3,opt,name=coinType,proto3" json:"coinType,omitempty"` // 玩家幣別
	Coin          int32  `protobuf:"varint,4,opt,name=coin,proto3" json:"coin,omitempty"`         // 玩家持有金額
	Avatar        string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`      // 玩家頭像
	Svt           string `protobuf:"bytes,6,opt,name=svt,proto3" json:"svt,omitempty"`            // 服務類型 ID（"lobby": 在大廳，其他: 在遊戲中，如 "baccarat"、"holdem"）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Player) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Player) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *Player) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *Player) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Player) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

type JoinLeave_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`           // 服務類型 ID（如 "baccarat"、"holdem"、"match"、"lobby"）
	Rid           string                 `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`           // 房間 ID
	IsJoin        bool                   `protobuf:"varint,3,opt,name=isJoin,proto3" json:"isJoin,omitempty"`    // 是否加入, true:加入, false:離開
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"` // 房間密碼（私人房間用）
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`       // 房間 Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLeave_Req) Reset() {
	*x = JoinLeave_Req{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLeave_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLeave_Req) ProtoMessage() {}

func (x *JoinLeave_Req) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLeave_Req.ProtoReflect.Descriptor instead.
func (*JoinLeave_Req) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *JoinLeave_Req) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *JoinLeave_Req) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *JoinLeave_Req) GetIsJoin() bool {
	if x != nil {
		return x.IsJoin
	}
	return false
}

func (x *JoinLeave_Req) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *JoinLeave_Req) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinLeave_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           string                 `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`     // 房間 ID
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 房間 Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLeave_Resp) Reset() {
	*x = JoinLeave_Resp{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLeave_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLeave_Resp) ProtoMessage() {}

func (x *JoinLeave_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLeave_Resp.ProtoReflect.Descriptor instead.
func (*JoinLeave_Resp) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *JoinLeave_Resp) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *JoinLeave_Resp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 聊天訊息
type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"` // 玩家 ID
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`   // 對話內容或符號
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *Chat) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Chat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EntryResponse：用於 holdem/entered 等進入遊戲的通知
type EntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 進入成功標記
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryResponse) Reset() {
	*x = EntryResponse{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryResponse) ProtoMessage() {}

func (x *EntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryResponse.ProtoReflect.Descriptor instead.
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *EntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MatchableRoomRegister：Game 呼叫 Match API 註冊或更新可被湊桌加入的房間（plan-simplify-match-dispatch §3.3）
type MatchableRoomRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	MinP          int32                  `protobuf:"varint,2,opt,name=min_p,json=minP,proto3" json:"min_p,omitempty"`
	RuleHash      string                 `protobuf:"bytes,3,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"`
	TableId       string                 `protobuf:"bytes,4,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	CurrentCount  int32                  `protobuf:"varint,5,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	NeedCount     int32                  `protobuf:"varint,6,opt,name=need_count,json=needCount,proto3" json:"need_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchableRoomRegister) Reset() {
	*x = MatchableRoomRegister{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchableRoomRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchableRoomRegister) ProtoMessage() {}

func (x *MatchableRoomRegister) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchableRoomRegister.ProtoReflect.Descriptor instead.
func (*MatchableRoomRegister) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *MatchableRoomRegister) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *MatchableRoomRegister) GetMinP() int32 {
	if x != nil {
		return x.MinP
	}
	return 0
}

func (x *MatchableRoomRegister) GetRuleHash() string {
	if x != nil {
		return x.RuleHash
	}
	return ""
}

func (x *MatchableRoomRegister) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *MatchableRoomRegister) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

func (x *MatchableRoomRegister) GetNeedCount() int32 {
	if x != nil {
		return x.NeedCount
	}
	return 0
}

// MatchableRoomRemove：Game 呼叫 Match API 移除可湊桌房間（滿員、開局或解散時）
type MatchableRoomRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	MinP          int32                  `protobuf:"varint,2,opt,name=min_p,json=minP,proto3" json:"min_p,omitempty"`
	RuleHash      string                 `protobuf:"bytes,3,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"`
	TableId       string                 `protobuf:"bytes,4,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchableRoomRemove) Reset() {
	*x = MatchableRoomRemove{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchableRoomRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchableRoomRemove) ProtoMessage() {}

func (x *MatchableRoomRemove) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchableRoomRemove.ProtoReflect.Descriptor instead.
func (*MatchableRoomRemove) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *MatchableRoomRemove) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *MatchableRoomRemove) GetMinP() int32 {
	if x != nil {
		return x.MinP
	}
	return 0
}

func (x *MatchableRoomRemove) GetRuleHash() string {
	if x != nil {
		return x.RuleHash
	}
	return ""
}

func (x *MatchableRoomRemove) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

// AddPlayerToRoomReq：Match Timer 呼叫 Game 補人時使用（plan-simplify-match-dispatch）
type AddPlayerToRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       string                 `protobuf:"bytes,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Uids          []uint32               `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	RuleHash      string                 `protobuf:"bytes,3,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"` // 該 queue 的 ruleHash，用於 matchable_rooms key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPlayerToRoomReq) Reset() {
	*x = AddPlayerToRoomReq{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPlayerToRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayerToRoomReq) ProtoMessage() {}

func (x *AddPlayerToRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayerToRoomReq.ProtoReflect.Descriptor instead.
func (*AddPlayerToRoomReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *AddPlayerToRoomReq) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *AddPlayerToRoomReq) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *AddPlayerToRoomReq) GetRuleHash() string {
	if x != nil {
		return x.RuleHash
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\x94\x01\n" +
	"\n" +
	"MatchEntry\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x1c\n" +
	"\tminPlayer\x18\x02 \x01(\rR\tminPlayer\x12\x1c\n" +
	"\tmaxPlayer\x18\x03 \x01(\rR\tmaxPlayer\x12$\n" +
	"\x06player\x18\x04 \x01(\v2\f.game.PlayerR\x06player\x12\x12\n" +
	"\x04rule\x18\x05 \x01(\tR\x04rule\"\xce\x01\n" +
	"\tMatchRoom\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\x10\n" +
	"\x03svt\x18\x02 \x01(\tR\x03svt\x12\x1c\n" +
	"\tminPlayer\x18\x03 \x01(\rR\tminPlayer\x12\x1c\n" +
	"\tmaxPlayer\x18\x04 \x01(\rR\tmaxPlayer\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\rR\tcreatedAt\x12&\n" +
	"\aplayers\x18\x06 \x03(\v2\f.game.PlayerR\aplayers\x12\x1b\n" +
	"\trule_hash\x18\a \x01(\tR\bruleHash\"\x90\x01\n" +
	"\x06Player\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bcoinType\x18\x03 \x01(\rR\bcoinType\x12\x12\n" +
	"\x04coin\x18\x04 \x01(\x05R\x04coin\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03svt\x18\x06 \x01(\tR\x03svt\"}\n" +
	"\rJoinLeave_Req\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\tR\x03rid\x12\x16\n" +
	"\x06isJoin\x18\x03 \x01(\bR\x06isJoin\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"8\n" +
	"\x0eJoinLeave_Resp\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\tR\x03rid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"<\n" +
	"\x04Chat\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\rEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xba\x01\n" +
	"\x15MatchableRoomRegister\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x13\n" +
	"\x05min_p\x18\x02 \x01(\x05R\x04minP\x12\x1b\n" +
	"\trule_hash\x18\x03 \x01(\tR\bruleHash\x12\x19\n" +
	"\btable_id\x18\x04 \x01(\tR\atableId\x12#\n" +
	"\rcurrent_count\x18\x05 \x01(\x05R\fcurrentCount\x12\x1d\n" +
	"\n" +
	"need_count\x18\x06 \x01(\x05R\tneedCount\"t\n" +
	"\x13MatchableRoomRemove\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x13\n" +
	"\x05min_p\x18\x02 \x01(\x05R\x04minP\x12\x1b\n" +
	"\trule_hash\x18\x03 \x01(\tR\bruleHash\x12\x19\n" +
	"\btable_id\x18\x04 \x01(\tR\atableId\"`\n" +
	"\x12AddPlayerToRoomReq\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\tR\atableId\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\rR\x04uids\x12\x1b\n" +
	"\trule_hash\x18\x03 \x01(\tR\bruleHash*3\n" +
	"\bRoomType\x12\n" +
	"\n" +
	"\x06PUBLIC\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\x0e\n" +
	"\n" +
	"TOURNAMENT\x10\x02B\x1dZ\x1binternal.proto/pb/game;gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_game_proto_goTypes = []any{
	(RoomType)(0),                 // 0: game.RoomType
	(*MatchEntry)(nil),            // 1: game.MatchEntry
	(*MatchRoom)(nil),             // 2: game.MatchRoom
	(*Player)(nil),                // 3: game.Player
	(*JoinLeave_Req)(nil),         // 4: game.JoinLeave_Req
	(*JoinLeave_Resp)(nil),        // 5: game.JoinLeave_Resp
	(*Chat)(nil),                  // 6: game.Chat
	(*EntryResponse)(nil),         // 7: game.EntryResponse
	(*MatchableRoomRegister)(nil), // 8: game.MatchableRoomRegister
	(*MatchableRoomRemove)(nil),   // 9: game.MatchableRoomRemove
	(*AddPlayerToRoomReq)(nil),    // 10: game.AddPlayerToRoomReq
}
var file_game_proto_depIdxs = []int32{
	3, // 0: game.MatchEntry.player:type_name -> game.Player
	3, // 1: game.MatchRoom.players:type_name -> game.Player
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
