#!/bin/bash
# Enable strict mode; pipefail may be unsupported on some shells, so guard it.
set -e
set -u
set -o pipefail 2>/dev/null || true

# === Path Setup ===
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SERVICES_DIR="$PROJECT_ROOT/services"
COCOS_DIR="$PROJECT_ROOT/clients/ts/cocos"
ROBOT_PROTO_DIR="$PROJECT_ROOT/clients/ts/robot/protos"
PROTO_ROOT="$PROJECT_ROOT/proto"
# Unity：基底目錄為 clients/csharp/unity，其下每個子目錄（且含 Assets/GameLink）視為一專案；系統 pb → Assets/GameLink/Pb/，遊戲 pb（依服務名對應專案名）→ Assets/Game/Pb/（遊戲層，不放在 GameLink）。遊戲腳本（如 AirMuseumExample、AirMuseumService）置於各專案 Assets/Script，不放在 GameLink。
UNITY_BASE_DIR="$PROJECT_ROOT/clients/csharp/unity"

# === Environment Preparation ===
GO_BIN_PATH="$(go env GOBIN 2>/dev/null || true)"
if [ -z "$GO_BIN_PATH" ]; then
  GO_BIN_PATH="$(go env GOPATH 2>/dev/null || true)/bin"
fi

if [ -n "$GO_BIN_PATH" ]; then
  export PATH="$PATH:$GO_BIN_PATH"
fi

NODE_BIN_PATH="$SCRIPT_DIR/node_modules/.bin"
if [ -d "$NODE_BIN_PATH" ]; then
  export PATH="$PATH:$NODE_BIN_PATH"
fi

if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN="python"
else
  PYTHON_BIN=""
fi

# === Helpers ===
declare -a INTERNAL_TS_TARGETS=()

add_internal_ts_target() {
  local dir="$1"
  if [ ! -d "$dir" ]; then
    return
  fi
  # 檢查數組是否為空，避免在 set -u 模式下報錯
  if [ "${#INTERNAL_TS_TARGETS[@]}" -gt 0 ]; then
    for existing in "${INTERNAL_TS_TARGETS[@]}"; do
      if [ "$existing" == "$dir" ]; then
        return
      fi
    done
  fi
  INTERNAL_TS_TARGETS+=("$dir")
}

# 檢查元素是否存在於數組中（用於替換關聯數組功能，兼容舊版 bash）
# 使用 ${arr[@]+"${arr[@]}"} 避免 set -u 下空陣列 unbound
array_contains() {
  local needle="$1"
  shift
  local haystack=("$@")
  local item
  for item in ${haystack[@]+"${haystack[@]}"}; do
    if [ "$item" == "$needle" ]; then
      return 0
    fi
  done
  return 1
}

# 將模組名中的連字符轉換為下劃線（用於 TypeScript 變數名）
sanitize_var_name() {
  echo "$1" | sed 's/-/_/g'
}

generate_ts_index() {
  local target_dir="$1"
  local index_file="$target_dir/index.ts"
  local module_paths=()
  local internal_module_paths=()
  local -a top_names=()
  local -a top_aliases=()
  local -a internal_names=()
  local -a internal_aliases=()
  local -a alias_map=()

  # 使用 while read 替代 mapfile（兼容舊版 bash）
  module_paths=()
  internal_module_paths=()
  local module_count=0
  while IFS= read -r file; do
    if [ -n "$file" ]; then
      module_paths+=("$file")
      module_count=$((module_count + 1))
    fi
  done < <(find "$target_dir" -maxdepth 1 -type f -name '*_pb.ts' -print | LC_ALL=C sort)
  # SDK 佈局：game-link-cocos-sdk/pb/*.ts
  local pb_dir="$target_dir/pb"
  local internal_count=0
  if [ -d "$pb_dir" ]; then
    while IFS= read -r file; do
      if [ -n "$file" ]; then
        internal_module_paths+=("$file")
        internal_count=$((internal_count + 1))
      fi
    done < <(find "$pb_dir" -maxdepth 1 -type f -name '*_pb.ts' -print | LC_ALL=C sort)
  fi
  # 舊佈局：internal/proto
  local internal_dir="$target_dir/internal/proto"
  if [ -d "$internal_dir" ] && [ "$internal_count" -eq 0 ]; then
    internal_module_paths=()
    while IFS= read -r file; do
      if [ -n "$file" ]; then
        internal_module_paths+=("$file")
        internal_count=$((internal_count + 1))
      fi
    done < <(find "$internal_dir" -maxdepth 1 -type f -name '*_pb.ts' -print | LC_ALL=C sort)
  fi

  if [ "$module_count" -eq 0 ] && [ "$internal_count" -eq 0 ]; then
    echo "    [WARN] $target_dir 未找到 *_pb.ts，跳過 index.ts 更新"
    return
  fi

  local module module_name rel_path alias var_name
  {
    echo "// Auto-generated by tools/gen-proto/run.sh. DO NOT EDIT!"
    echo
    for module_path in ${module_paths[@]+"${module_paths[@]}"}; do
      module="$(basename "$module_path" .ts)"
      var_name="$(sanitize_var_name "$module")"
      alias_map+=("$module")
      top_names+=("$module")
      top_aliases+=("$var_name")
      echo "import * as $var_name from './$module';"
    done
    for module_path in ${internal_module_paths[@]+"${internal_module_paths[@]}"}; do
      rel_path="${module_path#$target_dir/}"
      module_name="$(basename "$module_path" .ts)"
      # 如果 internal 模組名稱與頂層模組重複，跳過（優先使用頂層模組）
      if array_contains "$module_name" ${alias_map[@]+"${alias_map[@]}"}; then
        continue
      fi
      var_name="$(sanitize_var_name "$module_name")"
      alias_map+=("$module_name")
      internal_names+=("$module_name")
      internal_aliases+=("$var_name")
      echo "import * as $var_name from './${rel_path%.ts}';"
    done
    echo
    echo "export const proto = {"
    i=0
    while [ "$i" -lt "$module_count" ]; do
      echo "  ${top_aliases[$i]}: ${top_aliases[$i]},"
      i=$((i + 1))
    done
    i=0
    while [ "$i" -lt "$internal_count" ]; do
      echo "  ${internal_aliases[$i]}: ${internal_aliases[$i]},"
      i=$((i + 1))
    done
    echo "};"
  } > "$index_file"
}

sanitize_internal_ts() {
  local root="$1"
  local target_dir=""
  if [ -d "$root/pb" ]; then
    target_dir="$root/pb"
  elif [ -d "$root/internal/proto" ]; then
    target_dir="$root/internal/proto"
  fi
  if [ -z "$target_dir" ] || [ ! -d "$target_dir" ]; then
    return
  fi

  if [ -z "$PYTHON_BIN" ]; then
    echo "    [WARN] 找不到 python，無法重寫 internal TypeScript 宣告，請手動調整。"
    return
  fi

  "$PYTHON_BIN" - <<'PY' "$target_dir"
import sys
from pathlib import Path

target_dir = Path(sys.argv[1])
for path in target_dir.glob("*_pb.ts"):
    text = path.read_text(encoding="utf-8")
    text = text.replace("file_internal_proto_", "file_")
    text = text.replace("file_proto_", "file_")
    path.write_text(text, encoding="utf-8")
PY
}

# 僅用於 internal proto 的 ref 修正（傳入 SDK root 或 protos root）
sanitize_internal_ts_refs() {
  local target_dir="$1"

  if [ -z "$PYTHON_BIN" ]; then
    echo "    [WARN] 找不到 python，無法重寫 TypeScript 匯入路徑，請手動調整。"
    return
  fi

  "$PYTHON_BIN" - <<'PY' "$target_dir"
import sys
from pathlib import Path

target_dir = Path(sys.argv[1])
for path in target_dir.rglob("*.ts"):
    text = path.read_text(encoding="utf-8")
    if "file_internal_proto_" in text or "file_proto_" in text:
        text = text.replace("file_internal_proto_", "file_")
        text = text.replace("file_proto_", "file_")
    if "./proto/" in text:
        rel_parts = path.relative_to(target_dir).parts
        # 在 pb/ 或 internal/proto 目錄內時，同層引用改為 ./
        if len(rel_parts) >= 1 and rel_parts[0] == "pb":
            text = text.replace("./proto/", "./")
        elif len(rel_parts) >= 2 and rel_parts[0] == "internal" and rel_parts[1] == "proto":
            text = text.replace("./proto/", "./")
        else:
            text = text.replace("./proto/", "./internal/proto/")
    path.write_text(text, encoding="utf-8")
PY
}

# 將 game 的 assets/pb 內對 internal proto 的相對引用改為指向 game-link-cocos-sdk/pb
sanitize_game_pb_internal_imports() {
  local assets_pb_dir="$1"

  if [ -z "$PYTHON_BIN" ] || [ ! -d "$assets_pb_dir" ]; then
    return
  fi

  "$PYTHON_BIN" - <<'PY' "$assets_pb_dir"
import sys
from pathlib import Path

target = Path(sys.argv[1])
# internal proto 檔名（不含副檔名）
internal_names = ("gate", "game", "chat", "history", "profile")
for path in target.glob("*_pb.ts"):
    text = path.read_text(encoding="utf-8")
    for name in internal_names:
        old_import = f'"./{name}_pb"'
        new_import = f'"../game-link-cocos-sdk/pb/{name}_pb"'
        text = text.replace(old_import, new_import)
    path.write_text(text, encoding="utf-8")
PY
}

sanitize_ts_refs() {
  local target_dir="$1"

  if [ -z "$PYTHON_BIN" ]; then
    echo "    [WARN] 找不到 python，無法重寫 TypeScript 匯入路徑，請手動調整。"
    return
  fi

  "$PYTHON_BIN" - <<'PY' "$target_dir"
import sys
from pathlib import Path

target_dir = Path(sys.argv[1])
has_internal = (target_dir / "internal" / "proto").is_dir()
for path in target_dir.rglob("*.ts"):
    text = path.read_text(encoding="utf-8")
    if "file_internal_proto_" in text or "file_proto_" in text:
        text = text.replace("file_internal_proto_", "file_")
        text = text.replace("file_proto_", "file_")
    if "./proto/" in text:
        rel_parts = path.relative_to(target_dir).parts
        # 在 internal/proto 或 pb/ 或扁平目錄（如 assets/pb）內時，同層引用改為 ./
        if len(rel_parts) >= 2 and rel_parts[0] == "internal" and rel_parts[1] == "proto":
            text = text.replace("./proto/", "./")
        elif len(rel_parts) >= 1 and rel_parts[0] == "pb":
            text = text.replace("./proto/", "./")
        elif len(rel_parts) == 1 and not has_internal:
            # 扁平目錄（如 assets/pb），無 internal
            text = text.replace("./proto/", "./")
        else:
            text = text.replace("./proto/", "./internal/proto/")
    path.write_text(text, encoding="utf-8")
PY
}

# === Tool Checks ===
PROTOC_INCLUDE_PATH="$(protoc --print_include_path 2>/dev/null || true)"

if ! command -v protoc >/dev/null 2>&1; then
  echo "[ERROR] 未找到 protoc，請先安裝 protoc。"
  exit 1
fi

if ! command -v protoc-gen-go >/dev/null 2>&1; then
  echo "[ERROR] 未找到 protoc-gen-go，請執行：go install google.golang.org/protobuf/cmd/protoc-gen-go@latest"
  exit 1
fi

if ! command -v protoc-gen-go-grpc >/dev/null 2>&1; then
  echo "[ERROR] 未找到 protoc-gen-go-grpc，請執行：go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest"
  exit 1
fi

if ! command -v protoc-gen-es >/dev/null 2>&1; then
  echo "[ERROR] 未找到 protoc-gen-es，請在 tools/gen-proto 目錄執行：npm install"
  exit 1
fi

# === Cleanup ===
echo "開始清理並生成各服務的 Go proto..."

# === Locate Proto Files ===
if [ ! -d "$SERVICES_DIR" ]; then
  echo "[ERROR] 找不到 services 目錄：$SERVICES_DIR"
  exit 1
fi

proto_count=0
failed_proto=()

while IFS= read -r -d '' PROTO_FILE; do
  proto_count=$((proto_count + 1))
  PROTO_DIR="$(dirname "$PROTO_FILE")"
  SERVICE_DIR="$(dirname "$PROTO_DIR")"
  SERVICE_NAME="$(basename "$SERVICE_DIR")"
  GO_OUT_DIR="$PROTO_DIR/pb"
  TS_OUT_DIR="$COCOS_DIR/$SERVICE_NAME/assets/pb"

  echo "=== [$SERVICE_NAME] 處理 $(basename "$PROTO_FILE") ==="
  mkdir -p "$GO_OUT_DIR"
  find "$GO_OUT_DIR" -type f -name '*.pb.go' -delete 2>/dev/null || true

  if protoc \
    --proto_path="$PROTO_DIR" \
    --proto_path="$PROTO_ROOT" \
    --proto_path="$PROJECT_ROOT" \
    ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
    --go_out="$GO_OUT_DIR" \
    --go_opt=paths=source_relative \
    --go-grpc_out="$GO_OUT_DIR" \
    --go-grpc_opt=paths=source_relative \
    "$PROTO_FILE"; then
    echo "    -> Go proto 完成 ✅"
  else
    echo "    -> Go proto 失敗 ❌"
    failed_proto+=("$SERVICE_NAME(go)")
  fi

  if [ -d "$COCOS_DIR/$SERVICE_NAME" ]; then
    mkdir -p "$TS_OUT_DIR"
    echo "    -> 生成 TypeScript proto 到 $TS_OUT_DIR..."
    find "$TS_OUT_DIR" -maxdepth 1 -type f -name '*_pb.ts' -delete 2>/dev/null || true
    find "$TS_OUT_DIR" -maxdepth 1 -type f -name '*_pb.ts.meta' -delete 2>/dev/null || true

    if protoc \
      --proto_path="$PROTO_DIR" \
      --proto_path="$PROTO_ROOT" \
      --proto_path="$PROJECT_ROOT" \
      ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
      --es_out="$TS_OUT_DIR" \
      --es_opt=target=ts \
      "$PROTO_FILE"; then
      sanitize_ts_refs "$TS_OUT_DIR"
      sanitize_game_pb_internal_imports "$TS_OUT_DIR"
      generate_ts_index "$TS_OUT_DIR"
      echo "    -> TypeScript proto 完成 ✅"
    else
      echo "    -> TypeScript proto 失敗 ❌"
      failed_proto+=("$SERVICE_NAME(ts)")
    fi
  fi

  # 同時生成到 robot protos 目錄（robot 需要所有遊戲的 proto）
  if [ -d "$ROBOT_PROTO_DIR" ]; then
    echo "    -> 生成 TypeScript proto 到 robot 目錄..."
    ROBOT_TS_FILE="${SERVICE_NAME}_pb.ts"
    rm -f "$ROBOT_PROTO_DIR/$ROBOT_TS_FILE" "$ROBOT_PROTO_DIR/${ROBOT_TS_FILE}.meta" 2>/dev/null || true

    if protoc \
      --proto_path="$PROTO_DIR" \
      --proto_path="$PROTO_ROOT" \
      --proto_path="$PROJECT_ROOT" \
      ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
      --es_out="$ROBOT_PROTO_DIR" \
      --es_opt=target=ts \
      "$PROTO_FILE"; then
      sanitize_ts_refs "$ROBOT_PROTO_DIR"
      echo "    -> Robot TypeScript proto 完成 ✅"
    else
      echo "    -> Robot TypeScript proto 失敗 ❌"
      failed_proto+=("$SERVICE_NAME(robot-ts)")
    fi
  fi

  # Unity：專案名與服務名一致時，產出遊戲 pb 到該專案 Assets/Game/Pb（遊戲層，不放在 GameLink）
  UNITY_PROJECT_DIR="$UNITY_BASE_DIR/$SERVICE_NAME"
  if [ -d "$UNITY_PROJECT_DIR" ] && [ -d "$UNITY_PROJECT_DIR/Assets/GameLink" ]; then
    UNITY_GAME_PB_OUT="$UNITY_PROJECT_DIR/Assets/Game/Pb"
    mkdir -p "$UNITY_GAME_PB_OUT"
    find "$UNITY_GAME_PB_OUT" -type f -name '*.cs' -delete 2>/dev/null || true
    echo "    -> 生成 C# 遊戲 pb 到 $UNITY_GAME_PB_OUT..."
    if protoc \
      --proto_path="$PROTO_DIR" \
      --proto_path="$PROTO_ROOT" \
      --proto_path="$PROJECT_ROOT" \
      ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
      --csharp_out="$UNITY_GAME_PB_OUT" \
      "$PROTO_FILE"; then
      echo "    -> C# 遊戲 pb 完成 ✅"
    else
      echo "    -> C# 遊戲 pb 失敗 ❌"
      failed_proto+=("$SERVICE_NAME(unity-game-pb)")
    fi
  fi
done < <(find "$SERVICES_DIR" -mindepth 2 -maxdepth 3 -type f -name '*.proto' ! -path '*/pb/*' -print0)

# 生成 robot protos 目錄的 index.ts（包含所有遊戲的 proto）
if [ -d "$ROBOT_PROTO_DIR" ]; then
  echo ""
  echo "生成 robot protos index.ts..."
  generate_ts_index "$ROBOT_PROTO_DIR"
  echo "    -> Robot protos index.ts 完成 ✅"
fi

# Internal proto 僅輸出到每個遊戲的 game-link-cocos-sdk/pb（不再輸出到 shared/protos）
if [ -d "$COCOS_DIR" ]; then
  while IFS= read -r -d '' dir; do
    add_internal_ts_target "$dir"
  done < <(find "$COCOS_DIR" -type d -name 'game-link-cocos-sdk' -path '*/assets/*' -print0 2>/dev/null)
fi

# 確保 robot protos 目錄也被加入 proto 目標
if [ -d "$ROBOT_PROTO_DIR" ]; then
  add_internal_ts_target "$ROBOT_PROTO_DIR"
fi

if [ "${#INTERNAL_TS_TARGETS[@]}" -gt 0 ]; then
  for TS_TARGET_ROOT in "${INTERNAL_TS_TARGETS[@]}"; do
    # SDK 佈局：internal proto 輸出到 game-link-cocos-sdk/pb
    if [ -d "$TS_TARGET_ROOT/pb" ]; then
      find "$TS_TARGET_ROOT/pb" -type f -name '*_pb.ts' -delete 2>/dev/null || true
      find "$TS_TARGET_ROOT/pb" -type f -name '*_pb.ts.meta' -delete 2>/dev/null || true
    fi
    # 相容舊佈局 internal/proto
    TS_INTERNAL_DIR="$TS_TARGET_ROOT/internal/proto"
    if [ -d "$TS_INTERNAL_DIR" ]; then
      find "$TS_INTERNAL_DIR" -type f -name '*_pb.ts' -delete 2>/dev/null || true
      find "$TS_INTERNAL_DIR" -type f -name '*_pb.ts.meta' -delete 2>/dev/null || true
    fi
  done
fi

if [ -d "$PROTO_ROOT" ]; then
  echo ""
  echo "開始處理 proto..."
  # Unity：收集所有專案（UNITY_BASE_DIR 下含 Assets/GameLink 的子目錄），系統 pb 產出到各專案 Assets/GameLink/Pb
  declare -a UNITY_CSHARP_PROJECTS=()
  if [ -d "$UNITY_BASE_DIR" ]; then
    while IFS= read -r -d '' d; do
      if [ -d "$d/Assets/GameLink" ]; then
        UNITY_CSHARP_PROJECTS+=("$d")
      fi
    done < <(find "$UNITY_BASE_DIR" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
  fi
  for u in "${UNITY_CSHARP_PROJECTS[@]+"${UNITY_CSHARP_PROJECTS[@]}"}"; do
    mkdir -p "$u/Assets/GameLink/Pb"
    find "$u/Assets/GameLink/Pb" -type f -name '*.cs' -delete 2>/dev/null || true
  done
  while IFS= read -r -d '' PROTO_FILE; do
    proto_count=$((proto_count + 1))
    PROTO_BASENAME="$(basename "$PROTO_FILE" .proto)"
    GO_OUT_DIR="$PROTO_ROOT/pb/$PROTO_BASENAME"
    echo "=== [proto/$PROTO_BASENAME] generate $(basename "$PROTO_FILE") ==="
    mkdir -p "$GO_OUT_DIR"
    find "$GO_OUT_DIR" -type f -name '*.pb.go' -delete 2>/dev/null || true

    if protoc \
      --proto_path="$PROTO_ROOT" \
      --proto_path="$PROJECT_ROOT" \
      ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
      --go_out="$GO_OUT_DIR" \
      --go_opt=paths=source_relative \
      --go-grpc_out="$GO_OUT_DIR" \
      --go-grpc_opt=paths=source_relative \
      "$PROTO_FILE"; then
      echo "    -> Go proto 完成 ✅"
    else
      echo "    -> Go proto 失敗 ❌"
      failed_proto+=("proto/$PROTO_BASENAME(go)")
    fi

    if [ "${#INTERNAL_TS_TARGETS[@]}" -gt 0 ]; then
    for TS_TARGET_ROOT in "${INTERNAL_TS_TARGETS[@]}"; do
      if [ ! -d "$TS_TARGET_ROOT" ]; then
        echo "    [WARN] 找不到對應的 TypeScript 目錄：$TS_TARGET_ROOT，略過 TS 生成"
        continue
      fi

      # 每個遊戲的 SDK 目錄下輸出 internal proto 到 pb/
      TS_OUTPUT_DIR="$TS_TARGET_ROOT/pb"
      mkdir -p "$TS_OUTPUT_DIR"
      TS_FILE_NAME="${PROTO_BASENAME}_pb.ts"
      rm -f "$TS_OUTPUT_DIR/$TS_FILE_NAME" "$TS_OUTPUT_DIR/${TS_FILE_NAME}.meta"

      echo "    -> 生成 TypeScript proto 到 $TS_OUTPUT_DIR..."
      if protoc \
        --proto_path="$PROTO_ROOT" \
        --proto_path="$PROJECT_ROOT" \
        ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
        --es_out="$TS_OUTPUT_DIR" \
        --es_opt=target=ts \
        "$PROTO_FILE"; then
        sanitize_internal_ts_refs "$TS_TARGET_ROOT"
        generate_ts_index "$TS_TARGET_ROOT"
        sanitize_internal_ts "$TS_TARGET_ROOT"
        echo "    -> TypeScript proto 完成 ✅ ($TS_OUTPUT_DIR)"
      else
        echo "    -> TypeScript proto 失敗 ❌ ($TS_OUTPUT_DIR)"
        failed_proto+=("proto/$PROTO_BASENAME(ts->$TS_OUTPUT_DIR)")
      fi
    done
    fi

    # Unity：產出 C# 系統 pb 到各專案 Assets/GameLink/Pb（namespace 為 Gate、Game、Profile 等）
    for u in "${UNITY_CSHARP_PROJECTS[@]+"${UNITY_CSHARP_PROJECTS[@]}"}"; do
      UNITY_SYSTEM_PB_OUT="$u/Assets/GameLink/Pb"
      echo "    -> 生成 C# 系統 pb 到 $UNITY_SYSTEM_PB_OUT..."
      if protoc \
        --proto_path="$PROTO_ROOT" \
        --proto_path="$PROJECT_ROOT" \
        ${PROTOC_INCLUDE_PATH:+--proto_path="$PROTOC_INCLUDE_PATH"} \
        --csharp_out="$UNITY_SYSTEM_PB_OUT" \
        "$PROTO_FILE"; then
        echo "    -> C# 系統 pb 完成 ✅ ($u)"
      else
        echo "    -> C# 系統 pb 失敗 ❌ ($u)"
        failed_proto+=("proto/$PROTO_BASENAME(csharp->$u)")
      fi
    done
  done < <(find "$PROTO_ROOT" -type f -name '*.proto' ! -path '*/pb/*' -print0)
else
  echo "[WARN] missing proto directory, skip shared proto generation"
fi

if [ "$proto_count" -eq 0 ]; then
  echo "[WARN] 未找到任何可處理的 .proto 檔案。"
  exit 0
fi

if [ "${#failed_proto[@]}" -gt 0 ]; then
  echo ""
  echo "[ERROR] 以下 proto 生成失敗："
  for fp in "${failed_proto[@]}"; do
    echo " - $fp"
  done
  exit 1
fi

echo ""
echo "所有 proto 生成完成 ✅"
