// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: air_museum.proto

package air_museum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 玩家／投影端動作：此訊息代表什麼操作（entry、leave、input 等）
type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_ENTRY       Action = 1 // 入桌
	Action_ACTION_LEAVE       Action = 2 // 離桌
	Action_ACTION_INPUT       Action = 3 // 遊戲中輸入（axis_x/axis_y/seq 有效）
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_ENTRY",
		2: "ACTION_LEAVE",
		3: "ACTION_INPUT",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_ENTRY":       1,
		"ACTION_LEAVE":       2,
		"ACTION_INPUT":       3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_air_museum_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_air_museum_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{0}
}

// 遊戲階段／狀態（可入桌／Demo／遊戲中／滿員）
type GamePhase int32

const (
	GamePhase_GAME_PHASE_UNSPECIFIED   GamePhase = 0
	GamePhase_GAME_PHASE_WAITING_ENTRY GamePhase = 1 // 可入桌，等待玩家 entry
	GamePhase_GAME_PHASE_DEMO          GamePhase = 2 // Demo 狀態
	GamePhase_GAME_PHASE_PLAYING       GamePhase = 3 // 遊戲中
	GamePhase_GAME_PHASE_FULL          GamePhase = 4 // 滿員
)

// Enum value maps for GamePhase.
var (
	GamePhase_name = map[int32]string{
		0: "GAME_PHASE_UNSPECIFIED",
		1: "GAME_PHASE_WAITING_ENTRY",
		2: "GAME_PHASE_DEMO",
		3: "GAME_PHASE_PLAYING",
		4: "GAME_PHASE_FULL",
	}
	GamePhase_value = map[string]int32{
		"GAME_PHASE_UNSPECIFIED":   0,
		"GAME_PHASE_WAITING_ENTRY": 1,
		"GAME_PHASE_DEMO":          2,
		"GAME_PHASE_PLAYING":       3,
		"GAME_PHASE_FULL":          4,
	}
)

func (x GamePhase) Enum() *GamePhase {
	p := new(GamePhase)
	*p = x
	return p
}

func (x GamePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_air_museum_proto_enumTypes[1].Descriptor()
}

func (GamePhase) Type() protoreflect.EnumType {
	return &file_air_museum_proto_enumTypes[1]
}

func (x GamePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePhase.Descriptor instead.
func (GamePhase) EnumDescriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{1}
}

// 遊戲狀態：用於 pushGameState（投影端→Server）與 gameStateEvent（Server 廣播→所有玩家）
// 手柄端依 state 與 uids 取得房內成員列表
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         GamePhase              `protobuf:"varint,1,opt,name=state,proto3,enum=air_museum.GamePhase" json:"state,omitempty"` // 遊戲當前狀態
	Uids          []uint32               `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`                      // 當前房內玩家 uid 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_air_museum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_air_museum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetState() GamePhase {
	if x != nil {
		return x.State
	}
	return GamePhase_GAME_PHASE_UNSPECIFIED
}

func (x *GameState) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// 玩家→投影端統一承載：action（entry／leave／input）、uid、輸入軸與序號（input 時使用）
// 玩家送時 uid 可省略，由 Server 轉發時填入；投影端依 action 決定行為
type PlayerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=air_museum.Action" json:"action,omitempty"` // 此次代表的操作
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                              // 玩家端可不填，Server 轉發時填入
	AxisX         float32                `protobuf:"fixed32,3,opt,name=axis_x,json=axisX,proto3" json:"axis_x,omitempty"`            // 左右，建議 -1～1（action=INPUT 時使用）
	AxisY         float32                `protobuf:"fixed32,4,opt,name=axis_y,json=axisY,proto3" json:"axis_y,omitempty"`            // 上下，建議 -1～1（action=INPUT 時使用）
	Seq           uint32                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`                              // 序號（action=INPUT 時使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_air_museum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_air_museum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInput) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *PlayerInput) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInput) GetAxisX() float32 {
	if x != nil {
		return x.AxisX
	}
	return 0
}

func (x *PlayerInput) GetAxisY() float32 {
	if x != nil {
		return x.AxisY
	}
	return 0
}

func (x *PlayerInput) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// 錯誤通知：Server → Client（notify/error）；client 須訂閱此事件
type ErrorNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` // 錯誤訊息，如「主機已重連，請點擊登入重新 entry」
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorNotify) Reset() {
	*x = ErrorNotify{}
	mi := &file_air_museum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNotify) ProtoMessage() {}

func (x *ErrorNotify) ProtoReflect() protoreflect.Message {
	mi := &file_air_museum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNotify.ProtoReflect.Descriptor instead.
func (*ErrorNotify) Descriptor() ([]byte, []int) {
	return file_air_museum_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorNotify) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_air_museum_proto protoreflect.FileDescriptor

const file_air_museum_proto_rawDesc = "" +
	"\n" +
	"\x10air_museum.proto\x12\n" +
	"air_museum\"L\n" +
	"\tGameState\x12+\n" +
	"\x05state\x18\x01 \x01(\x0e2\x15.air_museum.GamePhaseR\x05state\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\rR\x04uids\"\x8b\x01\n" +
	"\vPlayerInput\x12*\n" +
	"\x06action\x18\x01 \x01(\x0e2\x12.air_museum.ActionR\x06action\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x15\n" +
	"\x06axis_x\x18\x03 \x01(\x02R\x05axisX\x12\x15\n" +
	"\x06axis_y\x18\x04 \x01(\x02R\x05axisY\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\rR\x03seq\"\x1f\n" +
	"\vErrorNotify\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg*V\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_ENTRY\x10\x01\x12\x10\n" +
	"\fACTION_LEAVE\x10\x02\x12\x10\n" +
	"\fACTION_INPUT\x10\x03*\x87\x01\n" +
	"\tGamePhase\x12\x1a\n" +
	"\x16GAME_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18GAME_PHASE_WAITING_ENTRY\x10\x01\x12\x13\n" +
	"\x0fGAME_PHASE_DEMO\x10\x02\x12\x16\n" +
	"\x12GAME_PHASE_PLAYING\x10\x03\x12\x13\n" +
	"\x0fGAME_PHASE_FULL\x10\x04B,Z\x1eair-museum/proto/pb;air_museum\xaa\x02\tAirMuseumb\x06proto3"

var (
	file_air_museum_proto_rawDescOnce sync.Once
	file_air_museum_proto_rawDescData []byte
)

func file_air_museum_proto_rawDescGZIP() []byte {
	file_air_museum_proto_rawDescOnce.Do(func() {
		file_air_museum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_air_museum_proto_rawDesc), len(file_air_museum_proto_rawDesc)))
	})
	return file_air_museum_proto_rawDescData
}

var file_air_museum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_air_museum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_air_museum_proto_goTypes = []any{
	(Action)(0),         // 0: air_museum.Action
	(GamePhase)(0),      // 1: air_museum.GamePhase
	(*GameState)(nil),   // 2: air_museum.GameState
	(*PlayerInput)(nil), // 3: air_museum.PlayerInput
	(*ErrorNotify)(nil), // 4: air_museum.ErrorNotify
}
var file_air_museum_proto_depIdxs = []int32{
	1, // 0: air_museum.GameState.state:type_name -> air_museum.GamePhase
	0, // 1: air_museum.PlayerInput.action:type_name -> air_museum.Action
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_air_museum_proto_init() }
func file_air_museum_proto_init() {
	if File_air_museum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_air_museum_proto_rawDesc), len(file_air_museum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_air_museum_proto_goTypes,
		DependencyIndexes: file_air_museum_proto_depIdxs,
		EnumInfos:         file_air_museum_proto_enumTypes,
		MessageInfos:      file_air_museum_proto_msgTypes,
	}.Build()
	File_air_museum_proto = out.File
	file_air_museum_proto_goTypes = nil
	file_air_museum_proto_depIdxs = nil
}
