// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: air_museum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AirMuseum {

  /// <summary>Holder for reflection information generated from air_museum.proto</summary>
  public static partial class AirMuseumReflection {

    #region Descriptor
    /// <summary>File descriptor for air_museum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AirMuseumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBhaXJfbXVzZXVtLnByb3RvEgphaXJfbXVzZXVtIj8KCUdhbWVTdGF0ZRIk",
            "CgVzdGF0ZRgBIAEoDjIVLmFpcl9tdXNldW0uR2FtZVBoYXNlEgwKBHVpZHMY",
            "AiADKA0ihQIKC1BsYXllcklucHV0EiIKBmFjdGlvbhgBIAEoDjISLmFpcl9t",
            "dXNldW0uQWN0aW9uEgsKA3VpZBgCIAEoDRIOCgZheGlzX3gYAyABKAISDgoG",
            "YXhpc195GAQgASgCEgsKA3NlcRgFIAEoDRIMCgRuYW1lGAYgASgJEgsKA2Fn",
            "ZRgHIAEoDRILCgNzZXgYCCABKAUSEwoLYXZhdGFyX2V5ZXMYCSABKAUSFgoO",
            "YXZhdGFyX2V5ZWJyb3cYCiABKAUSFAoMYXZhdGFyX21vdXRoGAsgASgFEhYK",
            "DmF2YXRhcl9nbGFzc2VzGAwgASgFEhUKDWF2YXRhcl9oZWxtZXQYDSABKAUi",
            "GgoLRXJyb3JOb3RpZnkSCwoDbXNnGAEgASgJKnIKBkFjdGlvbhIWChJBQ1RJ",
            "T05fVU5TUEVDSUZJRUQQABIQCgxBQ1RJT05fRU5UUlkQARIQCgxBQ1RJT05f",
            "TEVBVkUQAhIQCgxBQ1RJT05fSU5QVVQQAxIaChZBQ1RJT05fU0FWRV9BUFBF",
            "QVJBTkNFEAQqhwEKCUdhbWVQaGFzZRIaChZHQU1FX1BIQVNFX1VOU1BFQ0lG",
            "SUVEEAASHAoYR0FNRV9QSEFTRV9XQUlUSU5HX0VOVFJZEAESEwoPR0FNRV9Q",
            "SEFTRV9ERU1PEAISFgoSR0FNRV9QSEFTRV9QTEFZSU5HEAMSEwoPR0FNRV9Q",
            "SEFTRV9GVUxMEARCLFoeYWlyLW11c2V1bS9wcm90by9wYjthaXJfbXVzZXVt",
            "qgIJQWlyTXVzZXVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AirMuseum.Action), typeof(global::AirMuseum.GamePhase), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AirMuseum.GameState), global::AirMuseum.GameState.Parser, new[]{ "State", "Uids" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AirMuseum.PlayerInput), global::AirMuseum.PlayerInput.Parser, new[]{ "Action", "Uid", "AxisX", "AxisY", "Seq", "Name", "Age", "Sex", "AvatarEyes", "AvatarEyebrow", "AvatarMouth", "AvatarGlasses", "AvatarHelmet" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AirMuseum.ErrorNotify), global::AirMuseum.ErrorNotify.Parser, new[]{ "Msg" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 玩家／投影端動作：此訊息代表什麼操作（entry、leave、input 等）
  /// </summary>
  public enum Action {
    [pbr::OriginalName("ACTION_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 入桌
    /// </summary>
    [pbr::OriginalName("ACTION_ENTRY")] Entry = 1,
    /// <summary>
    /// 離桌
    /// </summary>
    [pbr::OriginalName("ACTION_LEAVE")] Leave = 2,
    /// <summary>
    /// 遊戲中輸入（axis_x/axis_y/seq 有效）
    /// </summary>
    [pbr::OriginalName("ACTION_INPUT")] Input = 3,
    /// <summary>
    /// 儲存裝扮／基本資料至 DB（填 name…avatar_helmet）
    /// </summary>
    [pbr::OriginalName("ACTION_SAVE_APPEARANCE")] SaveAppearance = 4,
  }

  /// <summary>
  /// 遊戲階段／狀態（可入桌／Demo／遊戲中／滿員）
  /// </summary>
  public enum GamePhase {
    [pbr::OriginalName("GAME_PHASE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 可入桌，等待玩家 entry
    /// </summary>
    [pbr::OriginalName("GAME_PHASE_WAITING_ENTRY")] WaitingEntry = 1,
    /// <summary>
    /// Demo 狀態
    /// </summary>
    [pbr::OriginalName("GAME_PHASE_DEMO")] Demo = 2,
    /// <summary>
    /// 遊戲中
    /// </summary>
    [pbr::OriginalName("GAME_PHASE_PLAYING")] Playing = 3,
    /// <summary>
    /// 滿員
    /// </summary>
    [pbr::OriginalName("GAME_PHASE_FULL")] Full = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 遊戲狀態：用於 pushGameState（投影端→Server）與 gameStateEvent（Server 廣播→所有玩家）
  /// 手柄端依 state 與 uids 取得房內成員列表
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameState : pb::IMessage<GameState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameState> _parser = new pb::MessageParser<GameState>(() => new GameState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AirMuseum.AirMuseumReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameState(GameState other) : this() {
      state_ = other.state_;
      uids_ = other.uids_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameState Clone() {
      return new GameState(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private global::AirMuseum.GamePhase state_ = global::AirMuseum.GamePhase.Unspecified;
    /// <summary>
    /// 遊戲當前狀態
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AirMuseum.GamePhase State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "uids" field.</summary>
    public const int UidsFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_uids_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> uids_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// 當前房內玩家 uid 列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Uids {
      get { return uids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      if(!uids_.Equals(other.uids_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (State != global::AirMuseum.GamePhase.Unspecified) hash ^= State.GetHashCode();
      hash ^= uids_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (State != global::AirMuseum.GamePhase.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      uids_.WriteTo(output, _repeated_uids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (State != global::AirMuseum.GamePhase.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      uids_.WriteTo(ref output, _repeated_uids_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (State != global::AirMuseum.GamePhase.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      size += uids_.CalculateSize(_repeated_uids_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameState other) {
      if (other == null) {
        return;
      }
      if (other.State != global::AirMuseum.GamePhase.Unspecified) {
        State = other.State;
      }
      uids_.Add(other.uids_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            State = (global::AirMuseum.GamePhase) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            uids_.AddEntriesFrom(input, _repeated_uids_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            State = (global::AirMuseum.GamePhase) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            uids_.AddEntriesFrom(ref input, _repeated_uids_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 玩家→投影端統一承載：action（entry／leave／input）、uid、輸入軸與序號（input 時使用）
  /// 玩家送時 uid 可省略，由 Server 轉發時填入；投影端依 action 決定行為
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerInput : pb::IMessage<PlayerInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerInput> _parser = new pb::MessageParser<PlayerInput>(() => new PlayerInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AirMuseum.AirMuseumReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput(PlayerInput other) : this() {
      action_ = other.action_;
      uid_ = other.uid_;
      axisX_ = other.axisX_;
      axisY_ = other.axisY_;
      seq_ = other.seq_;
      name_ = other.name_;
      age_ = other.age_;
      sex_ = other.sex_;
      avatarEyes_ = other.avatarEyes_;
      avatarEyebrow_ = other.avatarEyebrow_;
      avatarMouth_ = other.avatarMouth_;
      avatarGlasses_ = other.avatarGlasses_;
      avatarHelmet_ = other.avatarHelmet_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInput Clone() {
      return new PlayerInput(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private global::AirMuseum.Action action_ = global::AirMuseum.Action.Unspecified;
    /// <summary>
    /// 此次代表的操作
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AirMuseum.Action Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private uint uid_;
    /// <summary>
    /// 玩家端可不填，Server 轉發時填入
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "axis_x" field.</summary>
    public const int AxisXFieldNumber = 3;
    private float axisX_;
    /// <summary>
    /// 左右，建議 -1～1（action=INPUT 時使用）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AxisX {
      get { return axisX_; }
      set {
        axisX_ = value;
      }
    }

    /// <summary>Field number for the "axis_y" field.</summary>
    public const int AxisYFieldNumber = 4;
    private float axisY_;
    /// <summary>
    /// 上下，建議 -1～1（action=INPUT 時使用）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AxisY {
      get { return axisY_; }
      set {
        axisY_ = value;
      }
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 5;
    private uint seq_;
    /// <summary>
    /// 序號（action=INPUT 時使用）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 6;
    private string name_ = "";
    /// <summary>
    /// action=SAVE_APPEARANCE：客戶端填寫，與 PlayerPrefs air_museum_* 對齊；uid 仍以連線為準
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "age" field.</summary>
    public const int AgeFieldNumber = 7;
    private uint age_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Age {
      get { return age_; }
      set {
        age_ = value;
      }
    }

    /// <summary>Field number for the "sex" field.</summary>
    public const int SexFieldNumber = 8;
    private int sex_;
    /// <summary>
    /// 與客戶端註冊一致；可為 -1 未選
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Sex {
      get { return sex_; }
      set {
        sex_ = value;
      }
    }

    /// <summary>Field number for the "avatar_eyes" field.</summary>
    public const int AvatarEyesFieldNumber = 9;
    private int avatarEyes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarEyes {
      get { return avatarEyes_; }
      set {
        avatarEyes_ = value;
      }
    }

    /// <summary>Field number for the "avatar_eyebrow" field.</summary>
    public const int AvatarEyebrowFieldNumber = 10;
    private int avatarEyebrow_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarEyebrow {
      get { return avatarEyebrow_; }
      set {
        avatarEyebrow_ = value;
      }
    }

    /// <summary>Field number for the "avatar_mouth" field.</summary>
    public const int AvatarMouthFieldNumber = 11;
    private int avatarMouth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarMouth {
      get { return avatarMouth_; }
      set {
        avatarMouth_ = value;
      }
    }

    /// <summary>Field number for the "avatar_glasses" field.</summary>
    public const int AvatarGlassesFieldNumber = 12;
    private int avatarGlasses_;
    /// <summary>
    /// -1 表示未戴眼鏡
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarGlasses {
      get { return avatarGlasses_; }
      set {
        avatarGlasses_ = value;
      }
    }

    /// <summary>Field number for the "avatar_helmet" field.</summary>
    public const int AvatarHelmetFieldNumber = 13;
    private int avatarHelmet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarHelmet {
      get { return avatarHelmet_; }
      set {
        avatarHelmet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if (Uid != other.Uid) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AxisX, other.AxisX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AxisY, other.AxisY)) return false;
      if (Seq != other.Seq) return false;
      if (Name != other.Name) return false;
      if (Age != other.Age) return false;
      if (Sex != other.Sex) return false;
      if (AvatarEyes != other.AvatarEyes) return false;
      if (AvatarEyebrow != other.AvatarEyebrow) return false;
      if (AvatarMouth != other.AvatarMouth) return false;
      if (AvatarGlasses != other.AvatarGlasses) return false;
      if (AvatarHelmet != other.AvatarHelmet) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action != global::AirMuseum.Action.Unspecified) hash ^= Action.GetHashCode();
      if (Uid != 0) hash ^= Uid.GetHashCode();
      if (AxisX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AxisX);
      if (AxisY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AxisY);
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Age != 0) hash ^= Age.GetHashCode();
      if (Sex != 0) hash ^= Sex.GetHashCode();
      if (AvatarEyes != 0) hash ^= AvatarEyes.GetHashCode();
      if (AvatarEyebrow != 0) hash ^= AvatarEyebrow.GetHashCode();
      if (AvatarMouth != 0) hash ^= AvatarMouth.GetHashCode();
      if (AvatarGlasses != 0) hash ^= AvatarGlasses.GetHashCode();
      if (AvatarHelmet != 0) hash ^= AvatarHelmet.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action != global::AirMuseum.Action.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Uid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uid);
      }
      if (AxisX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(AxisX);
      }
      if (AxisY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(AxisY);
      }
      if (Seq != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Seq);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Age);
      }
      if (Sex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Sex);
      }
      if (AvatarEyes != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(AvatarEyes);
      }
      if (AvatarEyebrow != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(AvatarEyebrow);
      }
      if (AvatarMouth != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(AvatarMouth);
      }
      if (AvatarGlasses != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(AvatarGlasses);
      }
      if (AvatarHelmet != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(AvatarHelmet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action != global::AirMuseum.Action.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (Uid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Uid);
      }
      if (AxisX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(AxisX);
      }
      if (AxisY != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(AxisY);
      }
      if (Seq != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Seq);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Name);
      }
      if (Age != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Age);
      }
      if (Sex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Sex);
      }
      if (AvatarEyes != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(AvatarEyes);
      }
      if (AvatarEyebrow != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(AvatarEyebrow);
      }
      if (AvatarMouth != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(AvatarMouth);
      }
      if (AvatarGlasses != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(AvatarGlasses);
      }
      if (AvatarHelmet != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(AvatarHelmet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action != global::AirMuseum.Action.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
      }
      if (AxisX != 0F) {
        size += 1 + 4;
      }
      if (AxisY != 0F) {
        size += 1 + 4;
      }
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Seq);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Age != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Age);
      }
      if (Sex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Sex);
      }
      if (AvatarEyes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarEyes);
      }
      if (AvatarEyebrow != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarEyebrow);
      }
      if (AvatarMouth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarMouth);
      }
      if (AvatarGlasses != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarGlasses);
      }
      if (AvatarHelmet != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarHelmet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerInput other) {
      if (other == null) {
        return;
      }
      if (other.Action != global::AirMuseum.Action.Unspecified) {
        Action = other.Action;
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
      if (other.AxisX != 0F) {
        AxisX = other.AxisX;
      }
      if (other.AxisY != 0F) {
        AxisY = other.AxisY;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Age != 0) {
        Age = other.Age;
      }
      if (other.Sex != 0) {
        Sex = other.Sex;
      }
      if (other.AvatarEyes != 0) {
        AvatarEyes = other.AvatarEyes;
      }
      if (other.AvatarEyebrow != 0) {
        AvatarEyebrow = other.AvatarEyebrow;
      }
      if (other.AvatarMouth != 0) {
        AvatarMouth = other.AvatarMouth;
      }
      if (other.AvatarGlasses != 0) {
        AvatarGlasses = other.AvatarGlasses;
      }
      if (other.AvatarHelmet != 0) {
        AvatarHelmet = other.AvatarHelmet;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Action = (global::AirMuseum.Action) input.ReadEnum();
            break;
          }
          case 16: {
            Uid = input.ReadUInt32();
            break;
          }
          case 29: {
            AxisX = input.ReadFloat();
            break;
          }
          case 37: {
            AxisY = input.ReadFloat();
            break;
          }
          case 40: {
            Seq = input.ReadUInt32();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 56: {
            Age = input.ReadUInt32();
            break;
          }
          case 64: {
            Sex = input.ReadInt32();
            break;
          }
          case 72: {
            AvatarEyes = input.ReadInt32();
            break;
          }
          case 80: {
            AvatarEyebrow = input.ReadInt32();
            break;
          }
          case 88: {
            AvatarMouth = input.ReadInt32();
            break;
          }
          case 96: {
            AvatarGlasses = input.ReadInt32();
            break;
          }
          case 104: {
            AvatarHelmet = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Action = (global::AirMuseum.Action) input.ReadEnum();
            break;
          }
          case 16: {
            Uid = input.ReadUInt32();
            break;
          }
          case 29: {
            AxisX = input.ReadFloat();
            break;
          }
          case 37: {
            AxisY = input.ReadFloat();
            break;
          }
          case 40: {
            Seq = input.ReadUInt32();
            break;
          }
          case 50: {
            Name = input.ReadString();
            break;
          }
          case 56: {
            Age = input.ReadUInt32();
            break;
          }
          case 64: {
            Sex = input.ReadInt32();
            break;
          }
          case 72: {
            AvatarEyes = input.ReadInt32();
            break;
          }
          case 80: {
            AvatarEyebrow = input.ReadInt32();
            break;
          }
          case 88: {
            AvatarMouth = input.ReadInt32();
            break;
          }
          case 96: {
            AvatarGlasses = input.ReadInt32();
            break;
          }
          case 104: {
            AvatarHelmet = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 錯誤通知：Server → Client（notify/error）；client 須訂閱此事件
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ErrorNotify : pb::IMessage<ErrorNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ErrorNotify> _parser = new pb::MessageParser<ErrorNotify>(() => new ErrorNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ErrorNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AirMuseum.AirMuseumReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorNotify(ErrorNotify other) : this() {
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorNotify Clone() {
      return new ErrorNotify(this);
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 1;
    private string msg_ = "";
    /// <summary>
    /// 錯誤訊息，如「主機已重連，請點擊登入重新 entry」
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ErrorNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ErrorNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Msg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Msg.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ErrorNotify other) {
      if (other == null) {
        return;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
