// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gate.proto

package gate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// === 原 base.proto：閘道通用結構（Pack/UidReq/Auth/ErrorDetail）===
type Pack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackType      uint32                 `protobuf:"varint,1,opt,name=packType,proto3" json:"packType,omitempty"` // 0: request, 1: response 2: notify 3: trigger, 4: fetch
	ReqId         uint32                 `protobuf:"varint,2,opt,name=reqId,proto3" json:"reqId,omitempty"`
	Svt           string                 `protobuf:"bytes,3,opt,name=svt,proto3" json:"svt,omitempty"`       // 服務類型：baccarat, holdem, match, profile, gate 等（必需）
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // 方法名：bet, chat, getGameData, entry, leave 等（必需）
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`       // 錯誤訊息
	Info          *anypb.Any             `protobuf:"bytes,7,opt,name=info,proto3" json:"info,omitempty"`     // 請求參數或回應資料
	Detail        string                 `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"` // 錯誤細節 (JSON): {"loc":"bet.go:21","err":"db timeout","stack":"..."}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pack) Reset() {
	*x = Pack{}
	mi := &file_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pack) ProtoMessage() {}

func (x *Pack) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pack.ProtoReflect.Descriptor instead.
func (*Pack) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{0}
}

func (x *Pack) GetPackType() uint32 {
	if x != nil {
		return x.PackType
	}
	return 0
}

func (x *Pack) GetReqId() uint32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *Pack) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *Pack) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Pack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Pack) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Pack) GetInfo() *anypb.Any {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Pack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type UidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 僅需 UID 的請求（查詢個人資料、定位、狀態等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UidReq) Reset() {
	*x = UidReq{}
	mi := &file_gate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UidReq) ProtoMessage() {}

func (x *UidReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UidReq.ProtoReflect.Descriptor instead.
func (*UidReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{1}
}

func (x *UidReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Legal         bool                   `protobuf:"varint,1,opt,name=legal,proto3" json:"legal,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_gate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetLegal() bool {
	if x != nil {
		return x.Legal
	}
	return false
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Auth) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`     // 使用者友善訊息
	Loc           string                 `protobuf:"bytes,2,opt,name=loc,proto3" json:"loc,omitempty"`     // 位置 "bet.go:21"
	Stack         string                 `protobuf:"bytes,3,opt,name=stack,proto3" json:"stack,omitempty"` // 完整堆疊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_gate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetail) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ErrorDetail) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

func (x *ErrorDetail) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type PushErrorToUidsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []uint32               `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushErrorToUidsReq) Reset() {
	*x = PushErrorToUidsReq{}
	mi := &file_gate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushErrorToUidsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushErrorToUidsReq) ProtoMessage() {}

func (x *PushErrorToUidsReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushErrorToUidsReq.ProtoReflect.Descriptor instead.
func (*PushErrorToUidsReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{4}
}

func (x *PushErrorToUidsReq) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *PushErrorToUidsReq) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type EntryAndLeaveInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	Action        uint32                 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"` // 1: entry, 2: leave
	Uid           uint32                 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`       // 玩家 uid
	Rid           string                 `protobuf:"bytes,4,opt,name=rid,proto3" json:"rid,omitempty"`        // 房間 id（entry 回傳時由服務端填入，供客戶端寫入 GameDataStore）
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`        // 可選，離開原因等（如：餘額不足被剔除）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryAndLeaveInfo) Reset() {
	*x = EntryAndLeaveInfo{}
	mi := &file_gate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryAndLeaveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryAndLeaveInfo) ProtoMessage() {}

func (x *EntryAndLeaveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryAndLeaveInfo.ProtoReflect.Descriptor instead.
func (*EntryAndLeaveInfo) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{5}
}

func (x *EntryAndLeaveInfo) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *EntryAndLeaveInfo) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *EntryAndLeaveInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntryAndLeaveInfo) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *EntryAndLeaveInfo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// OnStateChangePayload 用於 Gate 推播 gate/onStateChange（如 Rollback 返回大廳）
type OnStateChangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`                    // 目標狀態，如 "lobby"
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                        // 任意字串，供客戶端切換頁面或提示用
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // 如 "m_20260215_123"，客戶端可校對後忽略過期推播
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnStateChangePayload) Reset() {
	*x = OnStateChangePayload{}
	mi := &file_gate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnStateChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnStateChangePayload) ProtoMessage() {}

func (x *OnStateChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnStateChangePayload.ProtoReflect.Descriptor instead.
func (*OnStateChangePayload) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{6}
}

func (x *OnStateChangePayload) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OnStateChangePayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OnStateChangePayload) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type PushToUidsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []uint32               `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	Svt           string                 `protobuf:"bytes,2,opt,name=svt,proto3" json:"svt,omitempty"`       // 服務類型：baccarat, holdem, match, profile, gate 等
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // 方法名：update, playerJoin, playerLeave, chat 等
	Data          *anypb.Any             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUidsReq) Reset() {
	*x = PushToUidsReq{}
	mi := &file_gate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUidsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUidsReq) ProtoMessage() {}

func (x *PushToUidsReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUidsReq.ProtoReflect.Descriptor instead.
func (*PushToUidsReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{7}
}

func (x *PushToUidsReq) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *PushToUidsReq) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *PushToUidsReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PushToUidsReq) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// KickUserReq 踢掉指定用戶連線的請求（kickUsers forward 用 uids；既有 uid/reason 可保留）
type KickUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`          // 要踢掉的用戶 UID（舊欄位，可保留）
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`     // 踢人原因：duplicate_login, admin_kick, etc.
	Uids          []uint32               `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"` // kickUsers 用，單人時傳 [uid]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserReq) Reset() {
	*x = KickUserReq{}
	mi := &file_gate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserReq) ProtoMessage() {}

func (x *KickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserReq.ProtoReflect.Descriptor instead.
func (*KickUserReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{8}
}

func (x *KickUserReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *KickUserReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KickUserReq) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// KickUserResp 踢人結果
type KickUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`            // 是否成功踢掉
	Uids          []uint32               `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"` // 未踢掉的用戶 UID list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResp) Reset() {
	*x = KickUserResp{}
	mi := &file_gate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResp) ProtoMessage() {}

func (x *KickUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResp.ProtoReflect.Descriptor instead.
func (*KickUserResp) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{9}
}

func (x *KickUserResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *KickUserResp) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

// ValidateReq/ValidateResp 用於 gate forward 路徑 auth/validate（Pack.Info）（原 gate-auth.proto）
type ValidateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	GateSid       string                 `protobuf:"bytes,2,opt,name=gate_sid,json=gateSid,proto3" json:"gate_sid,omitempty"` // 當前 Gate 實例 ID
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`                  // 裝置，如 web / iphone / android；可為空，空時後端視為 unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateReq) Reset() {
	*x = ValidateReq{}
	mi := &file_gate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateReq) ProtoMessage() {}

func (x *ValidateReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateReq.ProtoReflect.Descriptor instead.
func (*ValidateReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateReq) GetGateSid() string {
	if x != nil {
		return x.GateSid
	}
	return ""
}

func (x *ValidateReq) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ValidateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 通過時為玩家 uid，不通過為 0
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`  // 錯誤或附註訊息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResp) Reset() {
	*x = ValidateResp{}
	mi := &file_gate_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResp) ProtoMessage() {}

func (x *ValidateResp) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResp.ProtoReflect.Descriptor instead.
func (*ValidateResp) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateResp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ValidateResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// PingReq/PingResp 用於應用層 RTT 測量（gate/ping）
type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_gate_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{12}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_gate_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{13}
}

var File_gate_proto protoreflect.FileDescriptor

const file_gate_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"gate.proto\x12\x04gate\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xd0\x01\n" +
	"\x04Pack\x12\x1a\n" +
	"\bpackType\x18\x01 \x01(\rR\bpackType\x12\x14\n" +
	"\x05reqId\x18\x02 \x01(\rR\x05reqId\x12\x10\n" +
	"\x03svt\x18\x03 \x01(\tR\x03svt\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\x12(\n" +
	"\x04info\x18\a \x01(\v2\x14.google.protobuf.AnyR\x04info\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\"\x1a\n" +
	"\x06UidReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"D\n" +
	"\x04Auth\x12\x14\n" +
	"\x05legal\x18\x01 \x01(\bR\x05legal\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\"G\n" +
	"\vErrorDetail\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x10\n" +
	"\x03loc\x18\x02 \x01(\tR\x03loc\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\tR\x05stack\"Q\n" +
	"\x12PushErrorToUidsReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\rR\x04uids\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x11.gate.ErrorDetailR\x05error\"s\n" +
	"\x11EntryAndLeaveInfo\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x16\n" +
	"\x06action\x18\x02 \x01(\rR\x06action\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\rR\x03uid\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\tR\x03rid\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\"Y\n" +
	"\x14OnStateChangePayload\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\"w\n" +
	"\rPushToUidsReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\rR\x04uids\x12\x10\n" +
	"\x03svt\x18\x02 \x01(\tR\x03svt\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04data\"K\n" +
	"\vKickUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x12\n" +
	"\x04uids\x18\x03 \x03(\rR\x04uids\"2\n" +
	"\fKickUserResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\rR\x04uids\"V\n" +
	"\vValidateReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bgate_sid\x18\x02 \x01(\tR\agateSid\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"2\n" +
	"\fValidateResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\t\n" +
	"\aPingReq\"\n" +
	"\n" +
	"\bPingResp2\xda\x01\n" +
	"\vGateService\x12+\n" +
	"\aRequest\x12\n" +
	".gate.Pack\x1a\x14.google.protobuf.Any\x12,\n" +
	"\x06Notify\x12\n" +
	".gate.Pack\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aTrigger\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x05Fetch\x12\x16.google.protobuf.Empty\x1a\x14.google.protobuf.AnyB\x1dZ\x1binternal.proto/pb/gate;gateb\x06proto3"

var (
	file_gate_proto_rawDescOnce sync.Once
	file_gate_proto_rawDescData []byte
)

func file_gate_proto_rawDescGZIP() []byte {
	file_gate_proto_rawDescOnce.Do(func() {
		file_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_proto_rawDesc), len(file_gate_proto_rawDesc)))
	})
	return file_gate_proto_rawDescData
}

var file_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gate_proto_goTypes = []any{
	(*Pack)(nil),                 // 0: gate.Pack
	(*UidReq)(nil),               // 1: gate.UidReq
	(*Auth)(nil),                 // 2: gate.Auth
	(*ErrorDetail)(nil),          // 3: gate.ErrorDetail
	(*PushErrorToUidsReq)(nil),   // 4: gate.PushErrorToUidsReq
	(*EntryAndLeaveInfo)(nil),    // 5: gate.EntryAndLeaveInfo
	(*OnStateChangePayload)(nil), // 6: gate.OnStateChangePayload
	(*PushToUidsReq)(nil),        // 7: gate.PushToUidsReq
	(*KickUserReq)(nil),          // 8: gate.KickUserReq
	(*KickUserResp)(nil),         // 9: gate.KickUserResp
	(*ValidateReq)(nil),          // 10: gate.ValidateReq
	(*ValidateResp)(nil),         // 11: gate.ValidateResp
	(*PingReq)(nil),              // 12: gate.PingReq
	(*PingResp)(nil),             // 13: gate.PingResp
	(*anypb.Any)(nil),            // 14: google.protobuf.Any
	(*emptypb.Empty)(nil),        // 15: google.protobuf.Empty
}
var file_gate_proto_depIdxs = []int32{
	14, // 0: gate.Pack.info:type_name -> google.protobuf.Any
	3,  // 1: gate.PushErrorToUidsReq.error:type_name -> gate.ErrorDetail
	14, // 2: gate.PushToUidsReq.data:type_name -> google.protobuf.Any
	0,  // 3: gate.GateService.Request:input_type -> gate.Pack
	0,  // 4: gate.GateService.Notify:input_type -> gate.Pack
	15, // 5: gate.GateService.Trigger:input_type -> google.protobuf.Empty
	15, // 6: gate.GateService.Fetch:input_type -> google.protobuf.Empty
	14, // 7: gate.GateService.Request:output_type -> google.protobuf.Any
	15, // 8: gate.GateService.Notify:output_type -> google.protobuf.Empty
	15, // 9: gate.GateService.Trigger:output_type -> google.protobuf.Empty
	14, // 10: gate.GateService.Fetch:output_type -> google.protobuf.Any
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_gate_proto_init() }
func file_gate_proto_init() {
	if File_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_proto_rawDesc), len(file_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gate_proto_goTypes,
		DependencyIndexes: file_gate_proto_depIdxs,
		MessageInfos:      file_gate_proto_msgTypes,
	}.Build()
	File_gate_proto = out.File
	file_gate_proto_goTypes = nil
	file_gate_proto_depIdxs = nil
}
