// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLocateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocateResp) Reset() {
	*x = GetLocateResp{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocateResp) ProtoMessage() {}

func (x *GetLocateResp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocateResp.ProtoReflect.Descriptor instead.
func (*GetLocateResp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetLocateResp) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

// GetProfile_Resp will be packed into gate.Pack.info
type GetProfile_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"` // 0=root, 1=gm, 2=normal
	Svt           string                 `protobuf:"bytes,5,opt,name=svt,proto3" json:"svt,omitempty"`      // server type, e.g. lobby, baccarat, holdem
	Rid           string                 `protobuf:"bytes,6,opt,name=rid,proto3" json:"rid,omitempty"`      // room id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfile_Resp) Reset() {
	*x = GetProfile_Resp{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfile_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfile_Resp) ProtoMessage() {}

func (x *GetProfile_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfile_Resp.ProtoReflect.Descriptor instead.
func (*GetProfile_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfile_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetProfile_Resp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetProfile_Resp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetProfile_Resp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetProfile_Resp) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *GetProfile_Resp) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

type UpdateProfile_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Svt           string                 `protobuf:"bytes,4,opt,name=svt,proto3" json:"svt,omitempty"`
	Rid           string                 `protobuf:"bytes,5,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfile_Req) Reset() {
	*x = UpdateProfile_Req{}
	mi := &file_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfile_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile_Req) ProtoMessage() {}

func (x *UpdateProfile_Req) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile_Req.ProtoReflect.Descriptor instead.
func (*UpdateProfile_Req) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfile_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateProfile_Req) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfile_Req) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfile_Req) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *UpdateProfile_Req) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

// UpdateProfile_Resp will be packed into gate.Pack.info
type UpdateProfile_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Svt           string                 `protobuf:"bytes,4,opt,name=svt,proto3" json:"svt,omitempty"`
	Rid           string                 `protobuf:"bytes,5,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfile_Resp) Reset() {
	*x = UpdateProfile_Resp{}
	mi := &file_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfile_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfile_Resp) ProtoMessage() {}

func (x *UpdateProfile_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfile_Resp.ProtoReflect.Descriptor instead.
func (*UpdateProfile_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfile_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateProfile_Resp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfile_Resp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfile_Resp) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *UpdateProfile_Resp) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

// CheckPlayerStatus_Resp will be packed into gate.Pack.info
type CheckPlayerStatus_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IsBanned      bool                   `protobuf:"varint,2,opt,name=isBanned,proto3" json:"isBanned,omitempty"`
	CanJoinGame   bool                   `protobuf:"varint,3,opt,name=canJoinGame,proto3" json:"canJoinGame,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPlayerStatus_Resp) Reset() {
	*x = CheckPlayerStatus_Resp{}
	mi := &file_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPlayerStatus_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPlayerStatus_Resp) ProtoMessage() {}

func (x *CheckPlayerStatus_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPlayerStatus_Resp.ProtoReflect.Descriptor instead.
func (*CheckPlayerStatus_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPlayerStatus_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CheckPlayerStatus_Resp) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *CheckPlayerStatus_Resp) GetCanJoinGame() bool {
	if x != nil {
		return x.CanJoinGame
	}
	return false
}

func (x *CheckPlayerStatus_Resp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Wallet 相關消息（從 wallet service 整合而來）
type SetWalletDelta_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coinType,proto3" json:"coinType,omitempty"`
	Delta         int32                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // 增減原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWalletDelta_Req) Reset() {
	*x = SetWalletDelta_Req{}
	mi := &file_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWalletDelta_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWalletDelta_Req) ProtoMessage() {}

func (x *SetWalletDelta_Req) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWalletDelta_Req.ProtoReflect.Descriptor instead.
func (*SetWalletDelta_Req) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *SetWalletDelta_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetWalletDelta_Req) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *SetWalletDelta_Req) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *SetWalletDelta_Req) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetWalletDelta_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coinType,proto3" json:"coinType,omitempty"`
	NewBalance    int32                  `protobuf:"varint,3,opt,name=newBalance,proto3" json:"newBalance,omitempty"` // 更新後的餘額
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWalletDelta_Resp) Reset() {
	*x = SetWalletDelta_Resp{}
	mi := &file_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWalletDelta_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWalletDelta_Resp) ProtoMessage() {}

func (x *SetWalletDelta_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWalletDelta_Resp.ProtoReflect.Descriptor instead.
func (*SetWalletDelta_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *SetWalletDelta_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetWalletDelta_Resp) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *SetWalletDelta_Resp) GetNewBalance() int32 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

type GetWallet_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coinType,proto3" json:"coinType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWallet_Req) Reset() {
	*x = GetWallet_Req{}
	mi := &file_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWallet_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWallet_Req) ProtoMessage() {}

func (x *GetWallet_Req) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWallet_Req.ProtoReflect.Descriptor instead.
func (*GetWallet_Req) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

func (x *GetWallet_Req) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetWallet_Req) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

type GetWallet_Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CoinType      uint32                 `protobuf:"varint,2,opt,name=coinType,proto3" json:"coinType,omitempty"`
	Coin          int32                  `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWallet_Resp) Reset() {
	*x = GetWallet_Resp{}
	mi := &file_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWallet_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWallet_Resp) ProtoMessage() {}

func (x *GetWallet_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWallet_Resp.ProtoReflect.Descriptor instead.
func (*GetWallet_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{8}
}

func (x *GetWallet_Resp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetWallet_Resp) GetCoinType() uint32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *GetWallet_Resp) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

// GetGameInfo：依 svt 取得遊戲資訊（含 rule），供 Game service 啟動時拉取
type GetGameInfo_Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Svt           string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameInfo_Req) Reset() {
	*x = GetGameInfo_Req{}
	mi := &file_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameInfo_Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameInfo_Req) ProtoMessage() {}

func (x *GetGameInfo_Req) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameInfo_Req.ProtoReflect.Descriptor instead.
func (*GetGameInfo_Req) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{9}
}

func (x *GetGameInfo_Req) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

type GetGameInfo_Resp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Svt                    string                 `protobuf:"bytes,1,opt,name=svt,proto3" json:"svt,omitempty"`
	Rule                   string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`                                                                       // JSON string，即 player_modes 整份物件
	GameSettingsJson       string                 `protobuf:"bytes,3,opt,name=game_settings_json,json=gameSettingsJson,proto3" json:"game_settings_json,omitempty"`                     // JSON string，即 game_settings，結構同 rule，key 如 "standard"
	GameSettingsSchemaJson string                 `protobuf:"bytes,4,opt,name=game_settings_schema_json,json=gameSettingsSchemaJson,proto3" json:"game_settings_schema_json,omitempty"` // JSON string，即 game_settings_schema，欄位定義
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetGameInfo_Resp) Reset() {
	*x = GetGameInfo_Resp{}
	mi := &file_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameInfo_Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameInfo_Resp) ProtoMessage() {}

func (x *GetGameInfo_Resp) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameInfo_Resp.ProtoReflect.Descriptor instead.
func (*GetGameInfo_Resp) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{10}
}

func (x *GetGameInfo_Resp) GetSvt() string {
	if x != nil {
		return x.Svt
	}
	return ""
}

func (x *GetGameInfo_Resp) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *GetGameInfo_Resp) GetGameSettingsJson() string {
	if x != nil {
		return x.GameSettingsJson
	}
	return ""
}

func (x *GetGameInfo_Resp) GetGameSettingsSchemaJson() string {
	if x != nil {
		return x.GameSettingsSchemaJson
	}
	return ""
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\aprofile\"!\n" +
	"\rGetLocateResp\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\"\x91\x01\n" +
	"\x0fGetProfile_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03svt\x18\x05 \x01(\tR\x03svt\x12\x10\n" +
	"\x03rid\x18\x06 \x01(\tR\x03rid\"}\n" +
	"\x11UpdateProfile_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03svt\x18\x04 \x01(\tR\x03svt\x12\x10\n" +
	"\x03rid\x18\x05 \x01(\tR\x03rid\"~\n" +
	"\x12UpdateProfile_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03svt\x18\x04 \x01(\tR\x03svt\x12\x10\n" +
	"\x03rid\x18\x05 \x01(\tR\x03rid\"\x80\x01\n" +
	"\x16CheckPlayerStatus_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bisBanned\x18\x02 \x01(\bR\bisBanned\x12 \n" +
	"\vcanJoinGame\x18\x03 \x01(\bR\vcanJoinGame\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"p\n" +
	"\x12SetWalletDelta_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bcoinType\x18\x02 \x01(\rR\bcoinType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x05R\x05delta\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"c\n" +
	"\x13SetWalletDelta_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bcoinType\x18\x02 \x01(\rR\bcoinType\x12\x1e\n" +
	"\n" +
	"newBalance\x18\x03 \x01(\x05R\n" +
	"newBalance\"=\n" +
	"\rGetWallet_Req\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bcoinType\x18\x02 \x01(\rR\bcoinType\"R\n" +
	"\x0eGetWallet_Resp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1a\n" +
	"\bcoinType\x18\x02 \x01(\rR\bcoinType\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\x05R\x04coin\"#\n" +
	"\x0fGetGameInfo_Req\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\"\xa1\x01\n" +
	"\x10GetGameInfo_Resp\x12\x10\n" +
	"\x03svt\x18\x01 \x01(\tR\x03svt\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12,\n" +
	"\x12game_settings_json\x18\x03 \x01(\tR\x10gameSettingsJson\x129\n" +
	"\x19game_settings_schema_json\x18\x04 \x01(\tR\x16gameSettingsSchemaJsonB#Z!internal.proto/pb/profile;profileb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_profile_proto_goTypes = []any{
	(*GetLocateResp)(nil),          // 0: profile.GetLocateResp
	(*GetProfile_Resp)(nil),        // 1: profile.GetProfile_Resp
	(*UpdateProfile_Req)(nil),      // 2: profile.UpdateProfile_Req
	(*UpdateProfile_Resp)(nil),     // 3: profile.UpdateProfile_Resp
	(*CheckPlayerStatus_Resp)(nil), // 4: profile.CheckPlayerStatus_Resp
	(*SetWalletDelta_Req)(nil),     // 5: profile.SetWalletDelta_Req
	(*SetWalletDelta_Resp)(nil),    // 6: profile.SetWalletDelta_Resp
	(*GetWallet_Req)(nil),          // 7: profile.GetWallet_Req
	(*GetWallet_Resp)(nil),         // 8: profile.GetWallet_Resp
	(*GetGameInfo_Req)(nil),        // 9: profile.GetGameInfo_Req
	(*GetGameInfo_Resp)(nil),       // 10: profile.GetGameInfo_Resp
}
var file_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
